### ISSUE TITLE
TypeError: 0 has type numpy.int64, but expected one of: int

### ISSUE THREAD

**Issue by tomingliu** [daquexian/onnx-simplifier#1]
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/__main__.py", line 18, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/__main__.py", line 12, in main
    model_opt = onnxsim.simplify(args.input_model)
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/onnx_simplifier.py", line 179, in simplify
    model_opt = eliminate_const_nodes(model_ori, get_constant_nodes(model_ori), forward_all(model_ori))
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/onnx_simplifier.py", line 130, in eliminate_const_nodes
    vals=np.array(res[node.output[0]]).flatten().astype(get_np_type_from_elem_type(elem_type))
  File "/usr/local/lib/python3.6/dist-packages/onnx/helper.py", line 173, in make_tensor
    getattr(tensor, field).extend(vals)
TypeError: 0 has type numpy.int64, but expected one of: int

**Comment by daquexian** [comment]
Hi, thanks for your report!

Could you please provide the onnx model?

**Comment by tomingliu** [comment]
The model size is too big to attach. could you pls let me know your mailbox? I'm sending model file by email??

**Comment by daquexian** [comment]
All right. My email is daquexian566@gmail.com. Thanks!

**Comment by tomingliu** [comment]
check you mailbox now, already sent to you

**Comment by daquexian** [comment]
@tomingliu The model got simplified successfully on my side. I think the error you met is because of protobuf. Could you provide your protobuf version? It can be got by the following command

`python3 -c "import google.protobuf; print(google.protobuf.__version__)"`

**Comment by tomingliu** [comment]
Than you for reply quickly! Problem was solved by upgrading protobuf from 3.0.0 to 3.7.1
thanks again!

**Comment by daquexian** [comment]
Thanks for your report. Require protobuf>=3.7.0 now
