### ISSUE TITLE
KeyError: '73'

### ISSUE THREAD

**Issue by arnaudbrejeon** [daquexian/onnx-simplifier#10]
I get the following error on my model:
Simplifying...
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/onnxsim/__main__.py", line 24, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/onnxsim/__main__.py", line 17, in main
    model_opt = onnxsim.simplify(args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization)
  File "/usr/local/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 187, in simplify
    model_opt = eliminate_const_nodes(model_opt, get_constant_nodes(model_opt), forward_all(model_opt))
  File "/usr/local/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 122, in eliminate_const_nodes
    shape = res[node.output[0]].shape
KeyError: '73'

**Comment by arnaudbrejeon** [comment]
Here is the file
[m0.onnx.zip](https://github.com/daquexian/onnx-simplifier/files/3378712/m0.onnx.zip)

**Comment by arnaudbrejeon** [comment]
I managed to fix the problem by removing from const_nodes the nodes for which node.output[0] is not in the forwarded Dict.
I'm not 100% sure it is a good fix, though. Do you want me to make a Pull Request?

**Comment by daquexian** [comment]
@arnaudbrejeon sorry for the late reply.

It looks like a good way :) I will be very appreciated if you propose a pull request

**Comment by arnaudbrejeon** [comment]
I added the pull request. I may try to create a pull request to the onnx project to add your simplifier as an onnx optimizer.

**Comment by clw5180** [comment]
> I managed to fix the problem by removing from const_nodes the nodes for which node.output[0] is not in the forwarded Dict.
> I'm not 100% sure it is a good fix, though. Do you want me to make a Pull Request?

Oh my god, It works! Thanks a lot ! My error is due to the op onnx::Expand, maybe it's not in the forwarded Dict, and I don't understand why just 'remove' can works. Can you tell me something about it? Thank you very much! @arnaudbrejeon
