### ISSUE TITLE
ONNXruntimeError：could not find an implementation for the node BatchNormalization（6）

### ISSUE THREAD

**Issue by Hikaru-Furuta** [daquexian/onnx-simplifier#108]
### **Description of the bug**
I've tried to simplify an onnx-model that I had created using a module, "torch.onnx.export", from a ".pth"(Pytorch) model.
The following codes are for the implimentaition.
I believe the error was probably caused by compatibility of ONNX and Pytorch nodes.
Then I've searched the way to address this and tried several ways, which seems possible to work, only to find that they won't.
Could anyone solve this problem.

**Simplifying onnx-file**
In terminal,
`$ python3 -m onnxsim ctdet_coco_dla_2x.onnx Simple_ctdet_coco_dla_2x.onnx`
The error
`Simplifying...`
`Traceback (most recent call last):`
`File "/home/nel/anaconda3/envs/CenterNet_ONNX/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)`
`File "/home/nel/anaconda3/envs/CenterNet_ONNX/lib/python3.6/runpy.py", line 85, in _run_code exec(code, run_globals)`
`File "/home/nel/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/onnxsim/__main__.py", line 52, in <module>
 main()`
`File "/home/nel/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/onnxsim/__main__.py", line 40, in main
    args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization, skip_fuse_bn=not args.enable_fuse_bn, input_shapes=input_shapes, skipped_optimizers=args.skip_optimizer, skip_shape_inference=args.skip_shape_inference)`
`File "/home/nel/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 332, in simplify   model, const_nodes, input_shapes=input_shapes)`
`File "/home/nel/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 172, in forward_for_node_outputs  res = forward(model, input_shapes=input_shapes)`
`File "/home/nel/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 155, in forward), sess_options=sess_options, providers=['CPUExecutionProvider'])`
`File "/home/nel/.local/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 206, in __init__    self._create_inference_session(providers, provider_options)`
`File "/home/nel/.local/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 231, in _create_inference_session sess.initialize_session(providers or [], provider_options or [])`
`onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node BatchNormalization(6)`

**Converting a pytorch-file into onnx-file**
`from lib.models.networks.dlav0 import get_pose_net`
`from lib.models.model import load_model`
`import torch.onnx as onnx`
`import torch`
`from types import MethodType`
` `
`def forward(self, x):`
`	x = self.base(x)`
`	x = self.dla_up(x[self.first_level:])`
`	ret = []`
`	for head in self.heads:`
`		ret.append(self.__getattr__(head)(x))`
`	return ret`
` `
`input = torch.zeros([1, 3, 512, 512])`
`net = get_pose_net(34, {'hm':2, 'reg':2, 'wh':2})`
`net.forward = MethodType(forward, net)`
`  `
`load_model(net, '../models/ctdet_coco_dla_2x.pth')`
`onnx.export(net, input, '../models/ctdet_coco_dla_2x_2.onnx', verbose=True)`

**refference**
>Codes
>  'https://github.com/CaoWGG/TensorRT-CenterNet/issues/1'
Model 'ctdet_coco_dla_2x.pth'
> 'https://drive.google.com/open?id=1pl_-ael8wERdUREEnaIfqOV_VF2bEVRT'
Git/Centernet-Model
> https://github.com/xingyizhou/CenterNet

**Comment by daquexian** [comment]
Sorry for the late reply. Could you try upgrading your pytorch and exporting again?

**Comment by Hikaru-Furuta** [comment]
Thank you for replying.
I also have tried with torch==1.7.1, but 'Converting a pytorch-file into onnx-file' wouldn't work this version and I couldn't even convert because of the following error.
'ImportError : torch.utils.ffi is deprecated. Please use cpp extensions instead'
This doesn't make sense
