### ISSUE TITLE
ImportError: cannot import name 'get_all_providers' from 'onnxruntime.capi._pybind_state' 

### ISSUE THREAD

**Issue by glenn-jocher** [daquexian/onnx-simplifier#109]
Unable to import `onnxsim` after `pip install onnx-simplifier` with Python 3.8.0. We are attempting to integrate it into our YOLOv5 ONNX export workflow https://github.com/ultralytics/yolov5/issues/1597

Input:
```python
import onnxsim
```

Output:
```
/Users/glennjocher/PycharmProjects/yolov5-export/venv/lib/python3.8/site-packages/onnxruntime/capi/_pybind_state.py:14: UserWarning: Cannot load onnxruntime.capi. Error: 'dlopen(/Users/glennjocher/PycharmProjects/yolov5-export/venv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so, 2): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/glennjocher/PycharmProjects/yolov5-export/venv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so
  Reason: image not found'.
  warnings.warn("Cannot load onnxruntime.capi. Error: '{0}'.".format(str(e)))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/glennjocher/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-C/ch-0/203.5981.165/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/glennjocher/PycharmProjects/yolov5-export/venv/lib/python3.8/site-packages/onnxsim/__init__.py", line 1, in <module>
    from onnxsim.onnx_simplifier import simplify
  File "/Users/glennjocher/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-C/ch-0/203.5981.165/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/glennjocher/PycharmProjects/yolov5-export/venv/lib/python3.8/site-packages/onnxsim/onnx_simplifier.py", line 10, in <module>
    import onnxruntime as rt  # type: ignore
  File "/Users/glennjocher/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-C/ch-0/203.5981.165/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/glennjocher/PycharmProjects/yolov5-export/venv/lib/python3.8/site-packages/onnxruntime/__init__.py", line 13, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, \
ImportError: cannot import name 'get_all_providers' from 'onnxruntime.capi._pybind_state' (/Users/glennjocher/PycharmProjects/yolov5-export/venv/lib/python3.8/site-packages/onnxruntime/capi/_pybind_state.py)
```

<img width="1765" alt="Screen Shot 2020-12-22 at 3 23 20 PM" src="https://user-images.githubusercontent.com/26833433/102942519-72e89780-446a-11eb-9919-301736358e48.png">

**Comment by daquexian** [comment]
Thanks for your issue! 

It looks like openmp is missing: "Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib". After googling I find it is a prerequisite of onnxruntime on macos: https://www.onnxruntime.ai/docs/get-started/install.html. 

Could you please run `brew install libomp` and try again? 

Thanks!

**Comment by daquexian** [comment]
The latest onnx-simplifier depends on onnxruntime-noopenmp instead of onnxruntime so that openmp is not needed anymore :D

**Comment by daquexian** [comment]
It's so bad that onnxruntime-noopenmp doesn't have a macos version :| Reverted

**Comment by glenn-jocher** [comment]
@daquexian can we raise an issue on the onnxruntime-noopenmp repo for macos support?

**Comment by daquexian** [comment]
> @daquexian can we raise an issue on the onnxruntime-noopenmp repo for macos support?

@glenn-jocher according to https://github.com/microsoft/onnxruntime/issues/6511, there will be a macos version in the next release

**Comment by glenn-jocher** [comment]
@daquexian oh, perfect! Let's wait a bit then and revisit when macos support arrives :)

**Comment by sitting-duck** [comment]
Here is a link to a tutorial I wrote for how I fixed this on Windows 10 with Python 3.7.
I basically installed the Cuda toolkit and the CuDNN libraries to fix this issue.

The onnx runtime website shows how to install with pip install onnxruntime for CPU and pip install onnxruntime-gpu for CUDA support, but I think a lot of people fall into a gotcha because the OnnxRuntime site assumes you have all CUDA prereqs installed already and doesn't clearly list these on their website.

The tutorial is in written form with screencaps and also links to a video to show proof of fix as well.
Please feel free to leave comments here or on my medium if the solution does not work for you as I do check back and make fixes based on feedback. Thanks.
https://ashley-tharp.medium.com/install-onnxruntime-on-windows-2ad5ed8f4a50
