### ISSUE TITLE
Error when running onnx_simplifier on yolov5s

### ISSUE THREAD

**Issue by SAIL-LAB155** [daquexian/onnx-simplifier#113]
According to https://github.com/ultralytics/yolov5/issues/251, I converted yolov5s.pt to yolov5s.onnx. 
But yolov5s.onnx is weird in netron

![image](https://user-images.githubusercontent.com/56857281/104538620-2b16f380-5657-11eb-8cd0-755f80d8b7f6.png)
 And I run `python -m onnxsim yolov5s.onnx yolov5s_sim.onnx` 

`Simplifying...
(op_type:Slice, name:Slice_4): Inferred shape and existing shape differ in dimension 2: (640) vs (320)
Traceback (most recent call last):
  File "/home/hkuit164/anaconda3/envs/yolov5/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/hkuit164/anaconda3/envs/yolov5/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hkuit164/anaconda3/envs/yolov5/lib/python3.8/site-packages/onnxsim/__main__.py", line 52, in <module>
    main()
  File "/home/hkuit164/anaconda3/envs/yolov5/lib/python3.8/site-packages/onnxsim/__main__.py", line 39, in main
    model_opt, check_ok = onnxsim.simplify(
  File "/home/hkuit164/anaconda3/envs/yolov5/lib/python3.8/site-packages/onnxsim/onnx_simplifier.py", line 322, in simplify
    model = onnx.shape_inference.infer_shapes(model)
  File "/home/hkuit164/anaconda3/envs/yolov5/lib/python3.8/site-packages/onnx/shape_inference.py", line 35, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str, check_type)
RuntimeError: Inferred shape and existing shape differ in dimension 2: (640) vs (320)
`

**Comment by daquexian** [comment]
Could you please try `--skip-shape-inference`?

**Comment by Sean-hku** [comment]
Thx. 
There is no error when adding `--skip-shape-inference` 

![image](https://user-images.githubusercontent.com/63987404/104549126-2fe6a200-566d-11eb-8612-f31116f7f05f.png)
this is the result of onnx_simplifier on netron.
But when I try to convert to ncnn model , there is another error
` ./onnx2ncnn yolov5s_sin.onnx yolov5ss.param yolov5ss.bin
Unsupported slice step !
Unsupported slice step !
Unsupported slice step !
Unsupported slice step !
Unsupported slice step !
Unsupported slice step !
Unsupported slice step !
Unsupported slice step !
`
Is it the opset_version problem when I convert .pt to .onnx at first.

**Comment by daquexian** [comment]
@Sean-hku If you can read chinese, please check out https://zhuanlan.zhihu.com/p/275989233

**Comment by SAIL-LAB155** [comment]
Thank you!!!
