### ISSUE TITLE
Error when running onnx_simplifier on yolov3.weights

### ISSUE THREAD

**Issue by Sean-hku** [daquexian/onnx-simplifier#114]
Hi, I convert yolov3.weights to onnx version 

Export mode

    if ONNX_EXPORT:

        img = torch.zeros((1, 3) + img_size)  # (1, 3, 320, 192)

        torch.onnx.export(model, img, 'weights/export.onnx', verbose=True,opset_version=11)

        return
And the netron show the yolov3.onnx :
![image](https://user-images.githubusercontent.com/63987404/104539662-f441dd00-5658-11eb-834d-9ecaf6c2c5e9.png)
It look like incorrect.

So the runtimeerror occured when running `python -m onnxsim` 

`Simplifying...
(op_type:Slice, name:Slice_207): Inferred shape and existing shape differ in dimension 0: (2) vs (180)
Traceback (most recent call last):
  File "/home/hkuit164/anaconda3/envs/yolov3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hkuit164/anaconda3/envs/yolov3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hkuit164/anaconda3/envs/yolov3/lib/python3.6/site-packages/onnxsim/__main__.py", line 52, in <module>
    main()
  File "/home/hkuit164/anaconda3/envs/yolov3/lib/python3.6/site-packages/onnxsim/__main__.py", line 40, in main
    args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization, skip_fuse_bn=args.skip_fuse_bn, input_shapes=input_shapes, skipped_optimizers=args.skip_optimizer, skip_shape_inference=args.skip_shape_inference)
  File "/home/hkuit164/anaconda3/envs/yolov3/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 322, in simplify
    model = onnx.shape_inference.infer_shapes(model)
  File "/home/hkuit164/anaconda3/envs/yolov3/lib/python3.6/site-packages/onnx/shape_inference.py", line 35, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str, check_type)
RuntimeError: Inferred shape and existing shape differ in dimension 0: (2) vs (180)
`

**Comment by daquexian** [comment]
Sorry for the late reply. Please upgrade onnxsim to the latest version and try again. Thanks.
