### ISSUE TITLE
[BUG]  Segmentation fault etc 段错误等

### ISSUE THREAD

**Issue by benjaminwan** [daquexian/onnx-simplifier#115]
### 环境
* 系统：deepin20 x64
* python3.7.3
* protobuf 4.0.0rc2
* onnxoptimizer 0.1.2
* onnx 1.8.0
* onnxruntime 1.6.0
* numpy-1.19.5
* onnx-simplifier tag v0.2.22
* 所用的模型onnxruntime C++可以正常使用
* 以下的3个模型已发送到 daquexian566@gmail.com

### cls模型不带参数
```shell
python3 -m onnxsim ch_ppocr_mobile_v2.0_cls_infer.onnx cls-simp.onnx
Simplifying...
(op_type:Softmax, node name: Softmax@0): Inferred shape and existing shape differ in dimension 0: (1) vs (-1)
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/onnx_simplifier-0.0.0-py3.7.egg/onnxsim/__main__.py", line 52, in <module>
  File "/usr/local/lib/python3.7/dist-packages/onnx_simplifier-0.0.0-py3.7.egg/onnxsim/__main__.py", line 40, in main
  File "/usr/local/lib/python3.7/dist-packages/onnx_simplifier-0.0.0-py3.7.egg/onnxsim/onnx_simplifier.py", line 332, in simplify
  File "/usr/local/lib/python3.7/dist-packages/onnx_simplifier-0.0.0-py3.7.egg/onnxsim/onnx_simplifier.py", line 234, in optimize
  File "/usr/local/lib/python3.7/dist-packages/onnx-1.8.0-py3.7-linux-x86_64.egg/onnx/checker.py", line 102, in check_model
    C.check_model(protobuf_string)
onnx.onnx_cpp2py_export.checker.ValidationError: Node () has input size 2 not in range [min=1, max=1].
==> Context: Bad node spec: input: "Reshape@0" input: "375" output: "374" op_type: "Squeeze"
```

### cls模型带参数
```shell
python3 -m onnxsim ch_ppocr_mobile_v2.0_cls_infer.onnx cls-simp.onnx --skip-optimization --skip-shape-inference
Simplifying...
段错误
```

### det模型不带参数
```shell
python3 -m onnxsim ch_ppocr_mobile_v2.0_det_infer.onnx det-simp.onnx
Simplifying...
(op_type:Identity, node name: Identity@0): Inferred shape and existing shape differ in dimension 2: (32) vs (-1)
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/onnx_simplifier-0.0.0-py3.7.egg/onnxsim/__main__.py", line 52, in <module>
  File "/usr/local/lib/python3.7/dist-packages/onnx_simplifier-0.0.0-py3.7.egg/onnxsim/__main__.py", line 40, in main
  File "/usr/local/lib/python3.7/dist-packages/onnx_simplifier-0.0.0-py3.7.egg/onnxsim/onnx_simplifier.py", line 324, in simplify
  File "/usr/local/lib/python3.7/dist-packages/onnx_simplifier-0.0.0-py3.7.egg/onnxsim/onnx_simplifier.py", line 157, in forward_for_node_outputs
  File "/usr/local/lib/python3.7/dist-packages/onnx_simplifier-0.0.0-py3.7.egg/onnxsim/onnx_simplifier.py", line 140, in forward
  File "/usr/local/lib/python3.7/dist-packages/onnxruntime-1.6.0-py3.7-linux-x86_64.egg/onnxruntime/capi/onnxruntime_inference_collection.py", line 206, in __init__
    self._create_inference_session(providers, provider_options)
  File "/usr/local/lib/python3.7/dist-packages/onnxruntime-1.6.0-py3.7-linux-x86_64.egg/onnxruntime/capi/onnxruntime_inference_collection.py", line 228, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Type Error: Type (tensor()) of output arg (save_infer_model/scale_0.tmp_1) of node (Sigmoid@0) does not match expected type (tensor(float)).
```

### det模型带参数
```shell
python3 -m onnxsim ch_ppocr_mobile_v2.0_det_infer.onnx det-simp.onnx --skip-optimization --skip-shape-inference
Simplifying...
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/onnx_simplifier-0.0.0-py3.7.egg/onnxsim/__main__.py", line 52, in <module>
  File "/usr/local/lib/python3.7/dist-packages/onnx_simplifier-0.0.0-py3.7.egg/onnxsim/__main__.py", line 40, in main
  File "/usr/local/lib/python3.7/dist-packages/onnx_simplifier-0.0.0-py3.7.egg/onnxsim/onnx_simplifier.py", line 324, in simplify
  File "/usr/local/lib/python3.7/dist-packages/onnx_simplifier-0.0.0-py3.7.egg/onnxsim/onnx_simplifier.py", line 157, in forward_for_node_outputs
  File "/usr/local/lib/python3.7/dist-packages/onnx_simplifier-0.0.0-py3.7.egg/onnxsim/onnx_simplifier.py", line 142, in forward
  File "/usr/local/lib/python3.7/dist-packages/onnx_simplifier-0.0.0-py3.7.egg/onnxsim/onnx_simplifier.py", line 97, in generate_rand_input
  File "/usr/local/lib/python3.7/dist-packages/onnx_simplifier-0.0.0-py3.7.egg/onnxsim/onnx_simplifier.py", line 96, in <dictcomp>
  File "mtrand.pyx", line 1169, in numpy.random.mtrand.RandomState.rand
  File "mtrand.pyx", line 423, in numpy.random.mtrand.RandomState.random_sample
  File "_common.pyx", line 270, in numpy.random._common.double_fill
ValueError: negative dimensions are not allowed
```

### rec模型不带参数
```shell
python3 -m onnxsim ch_ppocr_mobile_v2.0_rec_infer.onnx rec-simp.onnx
Simplifying...
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/onnx_simplifier-0.0.0-py3.7.egg/onnxsim/__main__.py", line 52, in <module>
  File "/usr/local/lib/python3.7/dist-packages/onnx_simplifier-0.0.0-py3.7.egg/onnxsim/__main__.py", line 40, in main
  File "/usr/local/lib/python3.7/dist-packages/onnx_simplifier-0.0.0-py3.7.egg/onnxsim/onnx_simplifier.py", line 324, in simplify
  File "/usr/local/lib/python3.7/dist-packages/onnx_simplifier-0.0.0-py3.7.egg/onnxsim/onnx_simplifier.py", line 157, in forward_for_node_outputs
  File "/usr/local/lib/python3.7/dist-packages/onnx_simplifier-0.0.0-py3.7.egg/onnxsim/onnx_simplifier.py", line 140, in forward
  File "/usr/local/lib/python3.7/dist-packages/onnxruntime-1.6.0-py3.7-linux-x86_64.egg/onnxruntime/capi/onnxruntime_inference_collection.py", line 206, in __init__
    self._create_inference_session(providers, provider_options)
  File "/usr/local/lib/python3.7/dist-packages/onnxruntime-1.6.0-py3.7-linux-x86_64.egg/onnxruntime/capi/onnxruntime_inference_collection.py", line 228, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Type Error: Type (tensor()) of output arg (save_infer_model/scale_0.tmp_1) of node (Softmax@0) does not match expected type (tensor(float)).
```

### rec模型带参数
```shell
python3 -m onnxsim ch_ppocr_mobile_v2.0_rec_infer.onnx rec-simp.onnx --skip-optimization --skip-shape-inference --input-shape "1,3,32,128"
Simplifying...
段错误
```

**Comment by daquexian** [comment]
感谢提 issue！模型是从什么框架导出的呢

**Comment by benjaminwan** [comment]
Paddle2ONNX

**Comment by daquexian** [comment]
现在修复啦，请更新到最新的 v0.2.23 版本～

如果仍然有问题可以继续留言

**Comment by benjaminwan** [comment]
## Thanks!
## 感谢！
