### ISSUE TITLE
[BUG] simplifier a model with dynamic axis on batch got error

### ISSUE THREAD

**Issue by jinfagang** [daquexian/onnx-simplifier#117]
I have a model like this:

![image](https://user-images.githubusercontent.com/21303438/105964605-6684d980-60bd-11eb-80cc-10f403f4aa43.png)

when I want simplify it, I found this error.

```
print('Simplifying model...')
    model = onnx.load(onnx_model_name)
    model_simp, check = simplify(
        model, input_shapes={'input': [12, 3, 256, 192]})
    onnx.save('pose_sim.onnx', model_simp)
```

```
2021-01-27 16:23:31.362926687 [E:onnxruntime:, sequential_executor.cc:333 Execute] Non-zero status code returned while running Reshape node. Name:'Reshape_143' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:42 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, std::vector<long int>&) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{12}, requested shape:{}

Traceback (most recent call last):
  File "scripts/export_onnx.py", line 45, in <module>
    model, input_shapes={'input': [12, 3, 256, 192]})
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/onnx_simplifier.py", line 324, in simplify
    model, const_nodes, input_shapes=input_shapes)
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/onnx_simplifier.py", line 157, in forward_for_node_outputs
    res = forward(model, input_shapes=input_shapes)
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/onnx_simplifier.py", line 147, in forward
    outputs, inputs, run_options=run_options)))
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 124, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'Reshape_143' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:42 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, std::vector<long int>&) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{12}, requested shape:{}

```

**Comment by cyberpedestrian** [comment]
Hello. I confirm that. 
I think there is a problem of saving model with dynamic input/output.

**Comment by oelgendy** [comment]
Hi, 
Is this problem solved? I have a similar issue when I simplify an onnx file with dynamic batch/width/height

**Comment by bulatnv** [comment]
Hello @oelgendy.
I think it is.
Current simplifier is able to process models with dynamic batch-size. 

provide proper model input shape.
For example:
```
# simplifying dynamic model
simplified_model, check = simplify(optimized_model,
                                   input_shapes={'input': [1, 3, 608, 608]},
                                   dynamic_input_shape=True)
```

**Comment by oelgendy** [comment]
Thanks @bulatnv for your response. What about dynamic height and/or width? I tried it and found that it only makes the input and output tensors dynamic, but all intermediate tensors are static. Is there a way to fix this bug? Thanks in advance

**Comment by oelgendy** [comment]
Thanks @bulatnv . What about dynamic_output_shape? I am running an image enhancement network where the input and output images are dynamic and have the same dimensions
