### ISSUE TITLE
onnx error

### ISSUE THREAD

**Issue by onexuan** [daquexian/onnx-simplifier#122]
https://github.com/PeterL1n/BackgroundMattingV2

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.7/3.7.9_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python@3.7/3.7.9_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/onnxsim/__main__.py", line 52, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/onnxsim/__main__.py", line 40, in main
    args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization, skip_fuse_bn=args.skip_fuse_bn, input_shapes=input_shapes, skipped_optimizers=args.skip_optimizer, skip_shape_inference=args.skip_shape_inference)
  File "/usr/local/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 316, in simplify
    model, const_nodes, input_shapes=input_shapes)
  File "/usr/local/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 157, in forward_for_node_outputs
    res = forward(model, input_shapes=input_shapes)
  File "/usr/local/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 140, in forward
    ), sess_options=sess_options, providers=['CPUExecutionProvider'])
  File "/usr/local/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 206, in __init__
    self._create_inference_session(providers, provider_options)
  File "/usr/local/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 228, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Failed to load model with error: /Users/runner/work/1/s/onnxruntime/core/graph/graph.cc:1167 void onnxruntime::Graph::InitializeStateFromModelFileGraphProto() This is an invalid model. Graph output (897) does not exist in the graph.

**Comment by daquexian** [comment]
Thanks for your issue. I have reproduced the bug and found the root casue. Will fix it soon

**Comment by daquexian** [comment]
Please use `--skip-optimizer eliminate_identity` for now. This bug will be fixed in the next release of onnx optimizer

**Comment by daquexian** [comment]
It has been fixed in the latest release
