### ISSUE TITLE
大老师请帮忙看看，谢谢了

### ISSUE THREAD

**Issue by xiongzhu666** [daquexian/onnx-simplifier#127]
**Describe the bug**
Simplifying...
Traceback (most recent call last):
  File "D:\Anaconda3\envs\py3.6\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Anaconda3\envs\py3.6\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\nubia\AppData\Roaming\Python\Python36\site-packages\onnxsim\__main__.py", line 90, in <module>
    main()
  File "C:\Users\nubia\AppData\Roaming\Python\Python36\site-packages\onnxsim\__main__.py", line 78, in main
    custom_lib=args.custom_lib)
  File "C:\Users\nubia\AppData\Roaming\Python\Python36\site-packages\onnxsim\onnx_simplifier.py", line 465, in simplify
    model = fixed_point(model, infer_shapes_and_optimize, constant_folding)
  File "C:\Users\nubia\AppData\Roaming\Python\Python36\site-packages\onnxsim\onnx_simplifier.py", line 366, in fixed_point
    x = func_b(x)
  File "C:\Users\nubia\AppData\Roaming\Python\Python36\site-packages\onnxsim\onnx_simplifier.py", line 459, in constant_folding
    custom_lib=custom_lib)
  File "C:\Users\nubia\AppData\Roaming\Python\Python36\site-packages\onnxsim\onnx_simplifier.py", line 219, in forward_for_node_outputs
    custom_lib=custom_lib)
  File "C:\Users\nubia\AppData\Roaming\Python\Python36\site-packages\onnxsim\onnx_simplifier.py", line 185, in forward
    ), sess_options=sess_options, providers=['CPUExecutionProvider'])
  File "C:\Users\nubia\AppData\Roaming\Python\Python36\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 206, in __init__
    self._create_inference_session(providers, provider_options)
  File "C:\Users\nubia\AppData\Roaming\Python\Python36\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 228, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (Transpose_16) Op (Transpose) [TypeInferenceError] Invalid attribute perm {0, 2, 1}, input shape = {0}

**Comment by daquexian** [comment]
好，我明天看一下

xiongzhu666 <notifications@github.com> 于 2021年2月24日周三 下午8:08写道：

**Comment by daquexian** [comment]
你好，请问泥有给我发模型吗
