### ISSUE TITLE
[BUG] error when forward on MatMul:  Computeleft operand cannot broadcast on dim 1

### ISSUE THREAD

**Issue by yuxianzhi** [daquexian/onnx-simplifier#143]
**Describe the bug**

```
$ python3 -m onnxsim text/machine_comprehension/bert-squad/model/bertsquad-10.onnx a.onnx --input-shape segment_ids:0:1,256 input_ids:0:1,256 input_mask:0:1,256 unique_ids_raw_output___9:0:1
Simplifying...
2021-05-11 01:23:16.593612967 [E:onnxruntime:, sequential_executor.cc:281 Execute] Non-zero status code returned while running MatMul node. Name:'bert/encoder/layer_0/attention/self/MatMul' Status Message: Not satisfied: left_padded_dims_[idx_dim] == 1
matmul_helper.h:88 Computeleft operand cannot broadcast on dim 1
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/__main__.py", line 52, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/__main__.py", line 40, in main
    args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization, skip_fuse_bn=not args.enable_fuse_bn, input_shapes=input_shapes, skipped_optimizers=args.skip_optimizer, skip_shape_inference=args.skip_shape_inference)
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/onnx_simplifier.py", line 335, in simplify
    model, const_nodes, input_shapes=input_shapes)
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/onnx_simplifier.py", line 172, in forward_for_node_outputs
    res = forward(model, input_shapes=input_shapes)
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/onnx_simplifier.py", line 162, in forward
    outputs, inputs, run_options=run_options)))
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/session.py", line 111, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running MatMul node. Name:'bert/encoder/layer_0/attention/self/MatMul' Status Message: Not satisfied: left_padded_dims_[idx_dim] == 1
matmul_helper.h:88 Computeleft operand cannot broadcast on dim 1

```
**Model**
To reproduce the problem, please post download link of your model here, or send your model to daquexian566@gmail.com

model link: https://github.com/onnx/models/blob/master/text/machine_comprehension/bert-squad/model/bertsquad-10.onnx

**Comment by take-cheeze** [comment]
Not reproducible on current `master` (onnxsim 0.6.5.dev140, onnxruntime 1.27.0). Ran the exact command from this issue against `bertsquad-10.onnx` from the ONNX model zoo:

```
onnxsim bertsquad-10.onnx out.onnx --overwrite-input-shape segment_ids:0:1,256 input_ids:0:1,256 input_mask:0:1,256 unique_ids_raw_output___9:0:1
```

It simplifies cleanly (~15s) with no `MatMul` broadcasting error — `bert/encoder/layer_0/attention/self/MatMul` no longer fails, and the output passes `onnx.checker`. Closing as resolved; please reopen if you still hit this on a recent version.
