### ISSUE TITLE
onnx to simplier onnx 

### ISSUE THREAD

**Issue by henbucuoshanghai** [daquexian/onnx-simplifier#145]
python3 -m onnxsim aaaa.onnx sim.onnx
Traceback (most recent call last):
  File /anaconda3/envs/pytorch1.8/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "anaconda3/envs/pytorch1.8/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/anaconda3/envs/pytorch1.8/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/anaconda3/envs/pytorch1.8/lib/python3.8/site-packages/onnxsim/__init__.py", line 1, in <module>
    from onnxsim.onnx_simplifier import simplify
  File "/anaconda3/envs/pytorch1.8/lib/python3.8/site-packages/onnxsim/onnx_simplifier.py", line 8, in <module>
    import onnx.helper  # type: ignore
ModuleNotFoundError: No module named 'onnx.helper'; 'onnx' is not a package

why?  tks

**Comment by itsucks** [comment]
I got the same issue

**Comment by itsucks** [comment]
I suspect you had a folder or file named 'onnx' in current path

**Comment by beyzacevik** [comment]
I had the same error and yes I have got a script named onnx.py 🤣

**Comment by NoLoPhe** [comment]
Like me!
