### ISSUE TITLE
[BUG] simplify error for version<=0.3.0, dead loop for version 0.3.6

### ISSUE THREAD

**Issue by sshuair** [daquexian/onnx-simplifier#146]
**Describe the bug**
1. The version <= v0.3.0 got the follow error
    ```
    Traceback (most recent call last):
      File "./test/test.py", line 359, in <module>
        main()
      File "./test/test.py", line 299, in main
        simplify_onnx(temp_onnx, temp_onnx_simp)
      File "./test/test.py", line 189, in simplify_onnx
        model_simp, check = simplify(model)
      File "/home/xxx/miniconda3/envs/sl.seg.train/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 458, in simplify
        model = fixed_point(model, infer_shapes_and_optimize, constant_folding)
      File "/home/xxx/miniconda3/envs/sl.seg.train/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 365, in fixed_point
        x = func_b(func_a(x))
      File "/home/xxx/miniconda3/envs/sl.seg.train/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 452, in constant_folding
        custom_lib=custom_lib)
      File "/home/xxx/miniconda3/envs/sl.seg.train/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 219, in forward_for_node_outputs
        custom_lib=custom_lib)
      File "/home/xxx/miniconda3/envs/sl.seg.train/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 185, in forward
        ), sess_options=sess_options, providers=['CPUExecutionProvider'])
      File "/home/xxx/miniconda3/envs/sl.seg.train/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 280, in __init__
        self._create_inference_session(providers, provider_options)
      File "/home/xxx/miniconda3/envs/sl.seg.train/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 309, in _create_inference_session
        sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
    onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Type Error: Type parameter (T) bound to different types (tensor(float) and tensor(double) in node (Pow_520).
    ```
2. dead loop for version 0.3.6
    - It's get stucked simplify and not finished
 
**Model**
model link: https://www.dropbox.com/s/wedxdigz8adi7ep/model.onnx?dl=0

**Comment by kseniaryabinova** [comment]
Setting `skip_shape_inference=True` in `simplify` function works for me

Also the docs say:
>     :param skip_shape_inference: Skip shape inference (sometimes shape inference will crash)
