### ISSUE TITLE
onnx-simplify ssd model failed 

### ISSUE THREAD

**Issue by xiaodaxia** [daquexian/onnx-simplifier#19]
I generated onnx ssd model from here, according to the tutorial.
https://github.com/onnx/tensorflow-onnx/blob/master/tutorials/ConvertingSSDMobilenetToONNX.ipynb
Then I run the simplify procedure, and the error is as follows:

Simplifying...
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xiao/.local/lib/python3.7/site-packages/onnxsim/__main__.py", line 24, in <module>
    main()
  File "/home/xiao/.local/lib/python3.7/site-packages/onnxsim/__main__.py", line 17, in main
    model_opt = onnxsim.simplify(args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization)
  File "/home/xiao/.local/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 193, in simplify
    model_opt = optimize(model_opt)
  File "/home/xiao/.local/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 155, in optimize
    fixed_point=True)
  File "/home/xiao/.local/lib/python3.7/site-packages/onnx/optimizer.py", line 53, in optimize
    optimized_model_str = C.optimize_fixedpoint(model_str, passes)
IndexError: _Map_base::at

I want to know what is the error.

**Comment by Maximilianxu** [comment]
@xiaodaxia @daquexian Hi, I encountered the same error. Did you solve it?

**Comment by daquexian** [comment]
@xiaodaxia @Maximilianxu it is related with #23 #25. and it turns out to be a bug of ONNX: https://github.com/onnx/onnx/issues/2417

**Comment by daquexian** [comment]
It's better to track the issues about onnx optimizers in a single issue https://github.com/daquexian/onnx-simplifier/issues/25. Closing it.
