### ISSUE TITLE
ValidationError: Your model ir_version is higher than the checker's.

### ISSUE THREAD

**Issue by WQ1436317135** [daquexian/onnx-simplifier#2]
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/__main__.py", line 18, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/__main__.py", line 12, in main
    model_opt = onnxsim.simplify(args.input_model)
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/onnx_simplifier.py", line 179, in simplify
    model_opt = eliminate_const_nodes(model_ori, get_constant_nodes(model_ori), forward_all(model_ori))
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/onnx_simplifier.py", line 103, in forward_all
    model = onnx.utils.polish_model(model)
  File "/usr/local/lib/python3.6/dist-packages/onnx/utils.py", line 18, in polish_model
    onnx.checker.check_model(model)
  File "/usr/local/lib/python3.6/dist-packages/onnx/checker.py", line 82, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Your model ir_version is higher than the checker's.

**Comment by daquexian** [comment]
Please try to upgrade your onnx by a command like

```
pip install --upgrade onnx
```

**Comment by daquexian** [comment]
@WQ1436317135 Hi :) Is this issue solved by upgrading onnx?

**Comment by soham24** [comment]
yes

**Comment by daquexian** [comment]
Congratulations :)

**Comment by soham24** [comment]
thank you so much. for your big efforts! 
I am converting this to ncnn. convertion happens successfully  but output layers returns -100. on ncnn.
I am not sure this is the right place to ask this. Just asking if you can give me any direction :)

**Comment by EvanFodemski** [comment]
Came across this same issue now with IR version 9 to 10 

"onnx.onnx_cpp2py_export.checker.validationerror: your model ir_version 10 is higher than the checker's (9)."

I found that you can solve this while converting from .pt to  .onnx in my case in the changing opset level in the following comand

"yolo export model=./best.pt imgsz=640 format=onnx opset=10"

change 10 to 9 or whatever you need

"yolo export model=./best.pt imgsz=640 format=onnx opset=9"

This worked for me anyways, your issue is probably deeper in which case I personally would give up.

**Comment by aleeshajaganath** [comment]
for solving ir version issue check the version compatibility [https://onnxruntime.ai/docs/reference/compatibility.html](https://onnxruntime.ai/docs/reference/compatibility.html)
