### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SolomidHero** [daquexian/onnx-simplifier#206]
**Describe the bug**
Segmentation fault on onnx model conversion

It hapens on pytest stage

There is traceback
```pytb
convert_to_onnx.py:37: in simplify_onnx_model
    onnx_model, check = onnxsim.simplify(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

model = ir_version: 8
producer_name: "pytorch"
producer_version: "1.12.0"
graph {
  node {
    input: "onnx::Concat_1743"
    ...  dim {
            dim_param: "Addppg_dim_2"
          }
        }
      }
    }
  }
}
opset_import {
  version: 16
}

check_n = 0, perform_optimization = True, skip_fuse_bn = False
overwrite_input_shapes = {'input_feats': torch.Size([1, 117, 80])}
test_input_shapes = {'input_feats': torch.Size([1, 117, 80])}, skipped_optimizers = []
skip_shape_inference = False, input_data = None, dynamic_input_shape = True, custom_lib = None
include_subgraph = False, unused_output = None, tensor_size_threshold = 10737418240

    def simplify(
        model: Union[str, onnx.ModelProto],
        check_n: int = 0,
        perform_optimization: bool = True,
        skip_fuse_bn: bool = False,
        overwrite_input_shapes=None,
        test_input_shapes=None,
        skipped_optimizers: Optional[List[str]] = None,
        skip_shape_inference=False,
        input_data=None,
        dynamic_input_shape: bool = False,
        custom_lib: Optional[str] = None,
        include_subgraph: bool = False,
        unused_output: Optional[Sequence[str]] = None,
        tensor_size_threshold: str = MAX_TENSOR_SIZE_THRESHOLD,
        *,
        input_shapes=None,
    ) -> Tuple[onnx.ModelProto, bool]:
        """
        :param model: onnx ModelProto object or file path
        :param check_n: The simplified model will be checked for `check_n` times by random inputs
        :param perform_optimization: Whether to run onnx optimizer on the model
        :param skip_fuse_bn: Skip fuse_bn_into_conv onnx optimizer
        :param overwrite_input_shapes: If the model has dynamic input shape, user must pass a fixed input shape
                for generating random inputs and checking equality.
        :param test_input_shapes: If the model has dynamic input shape, user must pass a fixed input shape
                for generating random inputs and checking equality.
        :param skipped_optimizers: Skip some specific onnx optimizers
        :param skip_shape_inference: Skip shape inference (sometimes shape inference will crash)
        :param input_data: Feed custom input data for checking if needed
        :param dynamic_input_shape: Deprecated. Not needed anymore.
        :param custom_lib: onnxruntime custom ops's shared library
        :param include_subgraph: Simplify subgraph (e.g. true graph and false graph of "If" operator) instead of only the main graph
        :param unused_output: name of unused outputs that will be eliminated from the model
        :param input_shapes: Deprecated. Please use `overwrite_input_shapes` and/or `test_input_shapes` instead.
        :return: A tuple (simplified model, success(True) or failed(False))
        """
        if dynamic_input_shape:
            print(
                Text(
                    "WARNING: The argument `dynamic_input_shape=True` is not needed any more, onnxsim can now support dynamic input shapes natively, please refer to the latest documentation. An error will be raised in the future.",
                    style="bold red",
                )
            )
        if input_shapes is not None:
            print(
                Text(
                    "WARNING: The argument `input_shapes` is deprecated. Please use `overwrite_input_shapes` and/or `test_input_shapes` instead. An error will be raised in the future.",
                    style="bold red",
                )
            )
            overwrite_input_shapes = input_shapes
            test_input_shapes = input_shapes

        if not perform_optimization:
            # None means skip all optimizers
            skipped_optimizers = None
        elif skipped_optimizers is None:
            skipped_optimizers = []

        if skip_fuse_bn and skipped_optimizers is not None:
            skipped_optimizers.append("fuse_bn_into_conv")
        if isinstance(model, str):
            model = onnx.load(model)
        if overwrite_input_shapes is None:
            overwrite_input_shapes = {}
        overwrite_input_shapes = check_and_update_input_shapes(
            model, overwrite_input_shapes)
        test_input_shapes = check_and_update_input_shapes(
            model, test_input_shapes)

        for name, input_shape in overwrite_input_shapes.items():
            for ipt in model.graph.input:
                if ipt.name == name:
                    for i, dim in enumerate(ipt.type.tensor_type.shape.dim):
                        dim.dim_value = input_shape[i]
        if unused_output is not None:
            model = remove_unused_output(model, unused_output)

        # https://stackoverflow.com/a/60708339
        def parse_size(size: str) -> int:
            units = {"B": 1, "KB": 2**10, "MB": 2**20, "GB": 2**30, "TB": 2**40}
            size = size.upper()
            #print("parsing size ", size)
            if not re.match(r' ', size):
                size = re.sub(r'([KMGT]?B)', r' \1', size)
            number, unit = [string.strip() for string in size.split()]
            return int(float(number)*units[unit])

        tensor_size_threshold = parse_size(tensor_size_threshold)

>       model_opt_bytes = C.simplify(
            model.SerializeToString(),
            skipped_optimizers,
            True,
            not skip_shape_inference,
            tensor_size_threshold,
        )
E       MemoryError: std::bad_alloc

/usr/local/lib/python3.9/site-packages/onnxsim/onnx_simplifier.py:181: MemoryError
-------------------------------------- Captured stdout call --------------------------------------
WARNING: The argument `dynamic_input_shape=True` is not needed any more, onnxsim
can now support dynamic input shapes natively, please refer to the latest
documentation. An error will be raised in the future.
WARNING: The argument `input_shapes` is deprecated. Please use
`overwrite_input_shapes` and/or `test_input_shapes` instead. An error will be
raised in the future.
```

## model

sry, I am prohibited to share model

**Comment by gyenesvi** [comment]
I am getting the same error after upgrading onnxsim to the latest version (0.4.5). I also tried setting `tensor_size_threshold` to a smaller value but it did not help.

**Comment by daquexian** [comment]
> I am getting the same error after upgrading onnxsim to the latest version (0.4.5). I also tried setting tensor_size_threshold to a smaller value but it did not help.

Could you please send the model to me (daquexian566@gmail.com) so I can do some debugging? Thanks!

**Comment by gyenesvi** [comment]
Unfortunately, I got the model from a client and it's not clear if I can give it out. I'll let you know if it gets clarified.

**Comment by daquexian** [comment]
> Unfortunately, I got the model from a client and it's not clear if I can give it out. I'll let you know if it gets clarified.

Thanks!

**Comment by SolomidHero** [comment]
Hi, problem still persists.
Here is my minimal model for issue:
<img width="233" alt="Screenshot 2023-03-31 at 19 37 01" src="https://user-images.githubusercontent.com/28161779/229110135-4df3910b-3cba-41de-8fca-b35cd04c667f.png">

onnxsim version: `0.4.19`
```
onnxsim example.onnx example_sim.onnx --no-large-tensor
Simplifying...
[1]    34247 segmentation fault  onnxsim example.onnx example_sim.onnx --no-large-tensor
```
[example.onnx.zip](https://github.com/daquexian/onnx-simplifier/files/11121303/example.onnx.zip)

**Comment by SolomidHero** [comment]
I tried same conversion with latest model on provided `example.onnx` above 
Here is the error now
```bash
$ onnxsim --dynamic-input-shape example.onnx example_sim.onnx
Simplifying...
Traceback (most recent call last):
  File "/usr/local/bin/onnxsim", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/onnxsim/onnx_simplifier.py", line 659, in main
    model_opt, check_ok = simplify(
  File "/usr/local/lib/python3.9/site-packages/onnxsim/onnx_simplifier.py", line 587, in simplify
    model = fixed_point(model, constant_folding, infer_shapes_and_optimize)
  File "/usr/local/lib/python3.9/site-packages/onnxsim/onnx_simplifier.py", line 474, in fixed_point
    x = func_a(x)
  File "/usr/local/lib/python3.9/site-packages/onnxsim/onnx_simplifier.py", line 577, in constant_folding
    res = forward_for_node_outputs(model,
  File "/usr/local/lib/python3.9/site-packages/onnxsim/onnx_simplifier.py", line 303, in forward_for_node_outputs
    res = forward(model,
  File "/usr/local/lib/python3.9/site-packages/onnxsim/onnx_simplifier.py", line 272, in forward
    inputs.update(generate_specific_rand_input(model, {name: shape}))
  File "/usr/local/lib/python3.9/site-packages/onnxsim/onnx_simplifier.py", line 152, in generate_specific_rand_input
    raise RuntimeError(
RuntimeError: The shape of input "wav" has dynamic size "[1, 0]", please try "--dynamic-input-shape" or determine the input size manually by "--input-shape xxx". Run "python3 -m onnxsim -h" for details
```

my env:
```
$ pip freeze
markdown-it-py==2.2.0
mdurl==0.1.2
numpy==1.24.2
onnx==1.13.1
onnxsim==0.4.23
protobuf==3.20.3
Pygments==2.15.1
rich==13.3.4
typing_extensions==4.5.0
```

**Comment by SolomidHero** [comment]
Oh, nevermind on last message error, it was from version 0.3.19 of other env.
Actually with the env above everything is working.
> ```
> markdown-it-py==2.2.0
> mdurl==0.1.2
> numpy==1.24.2
> onnx==1.13.1
> onnxsim==0.4.23
> protobuf==3.20.3
> Pygments==2.15.1
> rich==13.3.4
> typing_extensions==4.5.0
> ```
