### ISSUE TITLE
安装的版本是0.4.4,再本地转失败,convermode.com可以转

### ISSUE THREAD

**Issue by cqray1990** [daquexian/onnx-simplifier#211]
**Describe the bug**

**Model**
To reproduce the problem, please post download link of your model here, or send your model to daquexian566@gmail.com

Traceback (most recent call last):
  File "/.local/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 189, in simplify
    tensor_size_threshold,
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/.local/lib/python3.6/site-packages/onnxsim/__main__.py", line 5, in <module>
    main()
  File "/.local/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 444, in main
    args.tensor_size_threshold,
  File "/.local/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 201, in simplify
    save_as_external_data=True,
TypeError: save_model() got an unexpected keyword argument 'save_as_external_data'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/.local/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 189, in simplify
    tensor_size_threshold,
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File local/lib/python3.6/site-packages/onnxsim/__main__.py", line 5, in <module>
    main()
  File .local/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 444, in main
    args.tensor_size_threshold,
  File "/.local/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 201, in simplify
    save_as_external_data=True,
TypeError: save_model() got an unexpected keyword argument 'save_as_external_data'

**Comment by daquexian** [comment]
thanks for your report! I'll fix it soon

**Comment by daquexian** [comment]
It will be fixed in 0.4.5 which will be published once the ci passes (in two hours)

**Comment by daquexian** [comment]
Please try again with 0.4.5, thanks~
