### ISSUE TITLE
google.protobuf.message.DecodeError: Protobuf decoding consumed too few bytes: 5 out of 105151288[BUG] 

### ISSUE THREAD

**Issue by Belinda-great** [daquexian/onnx-simplifier#22]
Thank you for your contribution!
I want ssd-pytorch2onnx, but there is error:
Simplifying...
D:\anaconda\lib\site-packages\onnx\__init__.py:94: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  decoded = cast(Optional[int], proto.ParseFromString(s))
Traceback (most recent call last):
  File "D:\anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\anaconda\lib\site-packages\onnxsim\__main__.py", line 24, in <module>
    main()
  File "D:\anaconda\lib\site-packages\onnxsim\__main__.py", line 17, in main
    model_opt = onnxsim.simplify(args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization)
  File "D:\anaconda\lib\site-packages\onnxsim\onnx_simplifier.py", line 192, in simplify
    model_ori = onnx.load(model_ori)
  File "D:\anaconda\lib\site-packages\onnx\__init__.py", line 114, in load_model
    model = load_model_from_string(s, format=format)
  File "D:\anaconda\lib\site-packages\onnx\__init__.py", line 151, in load_model_from_string
    return _deserialize(s, ModelProto())
  File "D:\anaconda\lib\site-packages\onnx\__init__.py", line 98, in _deserialize
    decoded, len(s)))
google.protobuf.message.DecodeError: Protobuf decoding consumed too few bytes: 5 out of 105151288

**Comment by daquexian** [comment]
Sorry for the late reply. If this issue is still valid, could you please send the model to daquexian566@gmail.com?

**Comment by daquexian** [comment]
I think the reason is the same as https://github.com/daquexian/onnx-simplifier/issues/29. You should simplify the **onnx model** but not pytorch model
