### ISSUE TITLE
[BUG] onnx.onnx_cpp2py_export.checker.ValidationError due to the seq2seq decoding not follow topologically sorted

### ISSUE THREAD

**Issue by iofu728** [daquexian/onnx-simplifier#221]
**Describe the bug**
When I run the onnxsim in a seq2seq model, it'll throw the ValidationError exception which shows the model doesn't follow topologically sorted.

**Steps to Reproduce the Issue**
I'll send the model to you by email.

**log**
```bash
➜  onnxsim a.onnx b.onnx
Simplifying...
Traceback (most recent call last):
  File "/home/hjiang/.local/bin/onnxsim", line 8, in <module>
    sys.exit(main())
  File "/home/hjiang/.local/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 444, in main
    args.tensor_size_threshold,
  File "/home/hjiang/.local/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 189, in simplify
    tensor_size_threshold,
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input '1863' of node:
name: MatMul_1618 OpType: MatMul
 is not output of any previous nodes.
```

**Comment by Eliza-and-black** [comment]
+1

**Comment by Eliza-and-black** [comment]
+1, have you solve this error? @iofu728
