### ISSUE TITLE
optimization failed on missing input nodes

### ISSUE THREAD

**Issue by nihui** [daquexian/onnx-simplifier#23]
git clone master，源码编译的版本
pytorch e4f5224ebde7a4490c8d42aa7032cc89ece68271
onnx ca1d5b7e0a3290a1419cb2020511df07d11287fe

[tmp.onnx.zip](https://github.com/daquexian/onnx-simplifier/files/3732807/tmp.onnx.zip)

```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nihui/.local/lib/python3.7/site-packages/onnxsim/__main__.py", line 24, in <module>
    main()
  File "/home/nihui/.local/lib/python3.7/site-packages/onnxsim/__main__.py", line 17, in main
    model_opt = onnxsim.simplify(args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization)
  File "/home/nihui/.local/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 197, in simplify
    model_opt = optimize(model_opt)
  File "/home/nihui/.local/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 157, in optimize
    fixed_point=True)
  File "/home/nihui/.local/lib/python3.7/site-packages/onnx-1.6.0-py3.7-linux-x86_64.egg/onnx/optimizer.py", line 53, in optimize
    optimized_model_str = C.optimize_fixedpoint(model_str, passes)
IndexError: _Map_base::at
```

在这里，unordered_map key 不存在
https://github.com/onnx/onnx/blob/ca1d5b7e0a3290a1419cb2020511df07d11287fe/onnx/common/ir_pb_converter.cc#L284

发现是因为 key 是 0.weight，input nodes 里没有找到，于是 hack 下，将 initializer node 也放在 input nodes 里面，但是又出现以下问题

似乎是因为 pytorch 导出的时候，没有把 weight 放在 input 里面？

```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nihui/.local/lib/python3.7/site-packages/onnxsim/__main__.py", line 24, in <module>
    main()
  File "/home/nihui/.local/lib/python3.7/site-packages/onnxsim/__main__.py", line 17, in main
    model_opt = onnxsim.simplify(args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization)
  File "/home/nihui/.local/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 202, in simplify
    model_opt = eliminate_const_nodes(model_opt, const_nodes, res)
  File "/home/nihui/.local/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 131, in eliminate_const_nodes
    vals=np.array(res[node.output[0]]).flatten().astype(get_np_type_from_elem_type(elem_type))
  File "/home/nihui/.local/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 67, in get_np_type_from_elem_type
    size = sizes[elem_type]
TypeError: tuple indices must be integers or slices, not NoneType
```

**Comment by nihui** [comment]
hi all
I finally resolved this issue

you have to add keep_initializers_as_inputs=True when exporting onnx

```
torch.onnx._export(model, x, "model.onnx", export_params=True, keep_initializers_as_inputs=True)
```

since this commit

https://github.com/pytorch/pytorch/commit/7583519b870e33ee3182f330c1bb8663559697b6

**Comment by daquexian** [comment]
看来是 onnx 的锅，onnx 的 bug 真多。。

**Comment by daquexian** [comment]
It's better to track the issues about onnx optimizers in a single issue https://github.com/daquexian/onnx-simplifier/issues/25. Closing it.
