### ISSUE TITLE
[BUG] 0.4.19和0.4.20存在的bug

### ISSUE THREAD

**Issue by luchangli03** [daquexian/onnx-simplifier#277]
**Describe the bug**
模型为opset 11，实际上没有split算子，但是onnxsim优化的时候报错说split算子存在问题。
但是把模型opset转到15-17后又不会报错。

Simplifying...
Traceback (most recent call last):
  File "/root/miniconda3/envs/lite/bin/onnxsim", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/lite/lib/python3.8/site-packages/onnxsim/onnx_simplifier.py", line 434, in main
    model_opt, check_ok = simplify(
  File "/root/miniconda3/envs/lite/lib/python3.8/site-packages/onnxsim/onnx_simplifier.py", line 186, in simplify
    model_opt_bytes = C.simplify(
onnx.onnx_cpp2py_export.checker.ValidationError: Node () has input size 2 not in range [min=1, max=1].

==> Context: Bad node spec for node. Name:  OpType: Split

**Comment by zhiqwang** [comment]
ort 原生能跑吗，如果能跑可以在 0.4.20 版本上加上 `--enable_onnxruntime_optimization` 试一下能不能 onnxsim

**Comment by luchangli03** [comment]
> ort 原生能跑吗，如果能跑可以在 0.4.20 版本上加上 `--enable_onnxruntime_optimization` 试一下能不能 onnxsim

还是会报错

**Comment by daquexian** [comment]
Thanks for your issue! Will fix it soon.
