### ISSUE TITLE
Error installing the onnx-simplifier

### ISSUE THREAD

**Issue by jan3657** [daquexian/onnx-simplifier#285]
I am getting the following error while trying to install onnx-simplifier, which is required for building ByteTracker. I would apprichiate any help I can get

   ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-umxpir8t/onnxoptimizer_c4beb98465c44311b34516513cd752f3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-umxpir8t/onnxoptimizer_c4beb98465c44311b34516513cd752f3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zb_56nh1/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/onnxoptimizer
         cwd: /tmp/pip-install-umxpir8t/onnxoptimizer_c4beb98465c44311b34516513cd752f3/
    Complete output (136 lines):
    fatal: not a git repository (or any of the parent directories): .git
    /usr/local/lib/python3.6/dist-packages/setuptools/dist.py:726: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
      % (opt, underscore_opt)
    /usr/local/lib/python3.6/dist-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
      SetuptoolsDeprecationWarning,
    /usr/local/lib/python3.6/dist-packages/setuptools/dist.py:726: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
      % (opt, underscore_opt)
    running install
    /usr/local/lib/python3.6/dist-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    running build
    running build_py
    running create_version
    running cmake_build
    --
    -- 3.20.1.0
    -- Found Python: /usr/bin/python3 (found version "3.6.9") found components: Interpreter Development Development.Module Development.Embed
    Generated: /tmp/pip-install-umxpir8t/onnxoptimizer_c4beb98465c44311b34516513cd752f3/.setuptools-cmake-build/third_party/onnx/onnx/onnx-ml.proto
    Generated: /tmp/pip-install-umxpir8t/onnxoptimizer_c4beb98465c44311b34516513cd752f3/.setuptools-cmake-build/third_party/onnx/onnx/onnx-operators-ml.proto
    Generated: /tmp/pip-install-umxpir8t/onnxoptimizer_c4beb98465c44311b34516513cd752f3/.setuptools-cmake-build/third_party/onnx/onnx/onnx-data.proto
    -- Could NOT find pybind11 (missing: pybind11_DIR)
    -- pybind11 v2.9.2
    --
    -- ******** Summary ********
    --   CMake version             : 3.26.3
    --   CMake command             : /usr/local/lib/python3.6/dist-packages/cmake/data/bin/cmake
    --   System                    : Linux
    --   C++ compiler              : /usr/bin/c++
    --   C++ compiler version      : 7.5.0
    --   CXX flags                 :  -Wnon-virtual-dtor
    --   Build type                : Release
    --   Compile definitions       : __STDC_FORMAT_MACROS
    --   CMAKE_PREFIX_PATH         :
    --   CMAKE_INSTALL_PREFIX      : /usr/local
    --   CMAKE_MODULE_PATH         :
    --
    --   ONNX version              : 1.13.0
    --   ONNX NAMESPACE            : onnx
    --   ONNX_USE_LITE_PROTO       : ON
    --   USE_PROTOBUF_SHARED_LIBS  : OFF
    --   Protobuf_USE_STATIC_LIBS  : ON
    --   ONNX_DISABLE_EXCEPTIONS   : OFF
    --   ONNX_WERROR               : OFF
    --   ONNX_BUILD_TESTS          : OFF
    --   ONNX_BUILD_BENCHMARKS     : OFF
    --
    --   Protobuf compiler         :
    --   Protobuf includes         :
    --   Protobuf libraries        :
    --   BUILD_ONNX_PYTHON         : ON
    --     Python version        :
    --     Python executable     : /usr/bin/python3
    --     Python includes       :
    -- Found Python: /usr/bin/python3 (found version "3.6.9") found components: Interpreter
    CMake Warning at CMakeLists.txt:87 (find_package):
      By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "pybind11",
      but CMake did not find one.
    
      Could not find a package configuration file provided by "pybind11"
      (requested version 2.2) with any of the following names:
    
        pybind11Config.cmake
        pybind11-config.cmake
    
      Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
      "pybind11_DIR" to a directory containing one of the above files.  If
      "pybind11" provides a separate development package or SDK, be sure it has
      been installed.
    
    
    -- Configuring done (2.8s)
    -- Generating done (0.5s)
    -- Build files have been written to: /tmp/pip-install-umxpir8t/onnxoptimizer_c4beb98465c44311b34516513cd752f3/.setuptools-cmake-build
    [ 12%] Built target libprotobuf-lite
    [ 41%] Built target libprotobuf
    [ 71%] Built target libprotoc
    [ 72%] Built target protoc
    [ 73%] Built target gen_onnx_proto
    [ 74%] Built target gen_onnx_data_proto
    [ 74%] Built target gen_onnx_operators_proto
    [ 78%] Built target onnx_proto
    [ 95%] Built target onnx
    [ 95%] Building CXX object CMakeFiles/onnx_optimizer.dir/onnxoptimizer/model_util.cc.o
    [ 95%] Built target onnx_cpp2py_export
    [ 96%] Building CXX object CMakeFiles/onnx_optimizer.dir/onnxoptimizer/pass_registry.cc.o
    [ 96%] Building CXX object CMakeFiles/onnx_optimizer.dir/onnxoptimizer/pass_manager.cc.o
    [ 96%] Building CXX object CMakeFiles/onnx_optimizer.dir/onnxoptimizer/passes/pass_util.cc.o
    /tmp/pip-install-umxpir8t/onnxoptimizer_c4beb98465c44311b34516513cd752f3/onnxoptimizer/model_util.cc:10:10: fatal error: filesystem: No such file or directory
     #include <filesystem>
              ^~~~~~~~~~~~
    compilation terminated.
    CMakeFiles/onnx_optimizer.dir/build.make:75: recipe for target 'CMakeFiles/onnx_optimizer.dir/onnxoptimizer/model_util.cc.o' failed
    make[2]: *** [CMakeFiles/onnx_optimizer.dir/onnxoptimizer/model_util.cc.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    CMakeFiles/Makefile2:155: recipe for target 'CMakeFiles/onnx_optimizer.dir/all' failed
    make[1]: *** [CMakeFiles/onnx_optimizer.dir/all] Error 2
    Makefile:135: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-umxpir8t/onnxoptimizer_c4beb98465c44311b34516513cd752f3/setup.py", line 347, in <module>
        'onnxoptimizer=onnxoptimizer:main',
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 68, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-umxpir8t/onnxoptimizer_c4beb98465c44311b34516513cd752f3/setup.py", line 223, in run
        self.run_command('cmake_build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-umxpir8t/onnxoptimizer_c4beb98465c44311b34516513cd752f3/setup.py", line 217, in run
        subprocess.check_call(build_args)
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '.', '--', '-j', '4']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-umxpir8t/onnxoptimizer_c4beb98465c44311b34516513cd752f3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-umxpir8t/onnxoptimizer_c4beb98465c44311b34516513cd752f3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zb_56nh1/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/onnxoptimizer Check the logs for full command output.

**Comment by twmht** [comment]
+1 same issue

**Comment by storm12t48** [comment]
+1

**Comment by TryTwoTop** [comment]
https://askubuntu.com/questions/1256440/how-to-get-libstdc-with-c17-filesystem-headers-on-ubuntu-18-bionic

install g++-8

**Comment by aidevmin** [comment]
+1

**Comment by Nobody-Zhang** [comment]
### I met the same problem as U and I solve it by updating gcc and g++ (mine: 9)

**Comment by TonyzBi** [comment]
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install gcc-9 g++-9

 sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 20 
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 20

I used the same as [TryTwoTop], but first add ppa source on old ubuntu version.
