### ISSUE TITLE
[BUG] I can't install onnx-simplifier on Jetson AGX orin 

### ISSUE THREAD

**Issue by storm12t48** [daquexian/onnx-simplifier#286]
I try every version same issues error installing this package on Jetson AGx orin 32 gb

```
Discarding https://files.pythonhosted.org/packages/1e/a8/de6f65f50ac5c457f0a0fe1de8802f681b0c20650e0db23560a675319f71/onnx-simplifier-0.4.13.tar.gz (from https://pypi.org/simple/onnx-simplifier/) (requires-python:>=3.6): Requested onnxsim from https://files.pythonhosted.org/packages/1e/a8/de6f65f50ac5c457f0a0fe1de8802f681b0c20650e0db23560a675319f71/onnx-simplifier-0.4.13.tar.gz (from super-gradients) has inconsistent name: expected 'onnx-simplifier', but metadata has 'onnxsim'
  Downloading onnx-simplifier-0.4.10.tar.gz (18.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.1/18.1 MB 13.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      fatal: not a git repository (or any of the parent directories): .git
      WARNING: The directory '/root/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
      /usr/lib/python3.8/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        File "/usr/lib/python3.8/site-packages/setuptools/_normalization.py", line 59, in safe_version
          return str(packaging.version.Version(v))
        File "/usr/lib/python3.8/site-packages/setuptools/_vendor/packaging/version.py", line 197, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'unknown'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-empzrljp/onnx-simplifier_571beb5c6f0641ebab4dd873e8819db8/setup.py", line 271, in <module>
          setuptools.setup(
        File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 491, in __init__
          self.patch_missing_pkg_info(attrs)
        File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 480, in patch_missing_pkg_info
          dist._version = _normalization.safe_version(str(attrs['version']))
        File "/usr/lib/python3.8/site-packages/setuptools/_normalization.py", line 62, in safe_version
          return str(packaging.version.Version(attempt))
        File "/usr/lib/python3.8/site-packages/setuptools/_vendor/packaging/version.py", line 197, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'unknown'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.


```

**Comment by storm12t48** [comment]
I find issue alone in this post thx @CNOCycle , i can install onnxsim==0.4.9 now 
[https://github.com/daquexian/onnx-simplifier/issues/214#issuecomment-1315465297]

**Comment by CNOCycle** [comment]
Actually, the issue about unknown version has been fixed since v0.4.11. You can simply install `onnxsim` using the command `pip3 install onnxsim`  on arm architecture without any problem. If you would like to install previous version, I need to build the package from the source code. The details can be fond in this [linke](https://github.com/daquexian/onnx-simplifier/issues/214#issuecomment-1315465297).

**Comment by storm12t48** [comment]
Honestly, it always gives me the same errors even on an nvidia container with onnxruntime normally which should work


![Screenshot from 2023-05-12 07-51-00](https://github.com/daquexian/onnx-simplifier/assets/40581062/d261ec48-55d2-46c6-a3c8-d19f332a1edc)

**Comment by emmmmm196** [comment]
我在orin上安装onnxsim失败了，安装的0.4.36版本，与该问题相同
pip3 install onnxsim
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting onnxsim
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ce/9e/f34238413ebeda9a3a8802feeaa5013934455466b9ab390b48ad9c7e184f/onnxsim-0.4.36.tar.gz (21.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      fatal: not a git repository (or any of the parent directories): .git
      /tmp/pip-install-6ibdq8sv/onnxsim_0956942a3b1f414caa5e31315760ca46/setup.py:28: DeprecationWarning: Use shutil.which instead of find_executable
        CMAKE = find_executable('cmake')
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-6ibdq8sv/onnxsim_0956942a3b1f414caa5e31315760ca46/setup.py", line 279, in <module>
          setuptools.setup(
        File "/home/xvair/anaconda3/envs/eloftr/lib/python3.8/site-packages/setuptools/__init__.py", line 116, in setup
          _install_setup_requires(attrs)
        File "/home/xvair/anaconda3/envs/eloftr/lib/python3.8/site-packages/setuptools/__init__.py", line 84, in _install_setup_requires
          dist = MinimalDistribution(attrs)
        File "/home/xvair/anaconda3/envs/eloftr/lib/python3.8/site-packages/setuptools/__init__.py", line 66, in __init__
          super().__init__(filtered)
        File "/home/xvair/anaconda3/envs/eloftr/lib/python3.8/site-packages/setuptools/dist.py", line 277, in __init__
          for ep in metadata.entry_points(group='distutils.setup_keywords'):
        File "/home/xvair/anaconda3/envs/eloftr/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 1001, in entry_points
          return EntryPoints(eps).select(**params)
        File "/home/xvair/anaconda3/envs/eloftr/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 999, in <genexpr>
          dist.entry_points for dist in _unique(distributions())
        File "/home/xvair/anaconda3/envs/eloftr/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 480, in entry_points
          return EntryPoints._from_text_for(self.read_text('entry_points.txt'), self)
        File "/home/xvair/anaconda3/envs/eloftr/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 905, in read_text
          return self._path.joinpath(filename).read_text(encoding='utf-8')
        File "/home/xvair/anaconda3/envs/eloftr/lib/python3.8/pathlib.py", line 1236, in read_text
          with self.open(mode='r', encoding=encoding, errors=errors) as f:
        File "/home/xvair/anaconda3/envs/eloftr/lib/python3.8/pathlib.py", line 1222, in open
          return io.open(self, mode, buffering, encoding, errors, newline,
        File "/home/xvair/anaconda3/envs/eloftr/lib/python3.8/pathlib.py", line 1078, in _opener
          return self._accessor.open(self, flags, mode)
      OSError: [Errno 74] Bad message: '/home/xvair/.local/lib/python3.8/site-packages/coloredlogs-15.0.1.dist-info/entry_points.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
