### ISSUE TITLE
[BUG] Gather indices element out of data bounds, idx=0 must be within the inclusive range [0,-1]

### ISSUE THREAD

**Issue by luchangli03** [daquexian/onnx-simplifier#303]
**Describe the bug**

2023-08-07 10:39:31.804936700 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Gather node. Name:'/layers.0/attn/Gather_10' Status Message: indices element out of data bounds, idx=0 must be within the inclusive range [0,-1]
Traceback (most recent call last):
  File "/root/miniconda3/envs/lite/bin/onnxsim", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/lite/lib/python3.9/site-packages/onnxsim/onnx_simplifier.py", line 479, in main
    model_opt, check_ok = simplify(
  File "/root/miniconda3/envs/lite/lib/python3.9/site-packages/onnxsim/onnx_simplifier.py", line 197, in simplify
    model_opt_bytes = C.simplify(
  File "/root/miniconda3/envs/lite/lib/python3.9/site-packages/onnxsim/onnx_simplifier.py", line 258, in Run
    output_arrs = sess.run(output_names, inputs, run_options=run_options)
  File "/root/miniconda3/envs/lite/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 217, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Gather node. Name:'/layers.0/attn/Gather_10' Status Message: indices element out of data bounds, idx=0 must be within the inclusive range [0,-1]

**Model**
To reproduce the problem, please post download link of your model here, or send your model to daquexian566@gmail.com

Qwen 7b chat onnx decoder exported by 
https://github.com/luchangli03/export_llama_as_onnx/tree/main

**Comment by warmtan** [comment]
indices element out of data bounds, idx=0 must be within the inclusive range [0,-1],me too
