### ISSUE TITLE
[BUG] RuntimeError: /project/third_party/onnx-optimizer/third_party/onnx/onnx/common/ir.h:1372: eraseOutput: Assertion `outputs_[i]->uses().empty()` failed

### ISSUE THREAD

**Issue by luchangli03** [daquexian/onnx-simplifier#341]
**Describe the bug**
I use onnxsim-0.4.36 to simpily a model and get this error:

Traceback (most recent call last):
  File "/root/miniconda3/envs/lite/bin/onnxsim", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/lite/lib/python3.9/site-packages/onnxsim/onnx_simplifier.py", line 489, in main
    model_opt, check_ok = simplify(
  File "/root/miniconda3/envs/lite/lib/python3.9/site-packages/onnxsim/onnx_simplifier.py", line 199, in simplify
    model_opt_bytes = C.simplify(
RuntimeError: /project/third_party/onnx-optimizer/third_party/onnx/onnx/common/ir.h:1372: eraseOutput: Assertion `outputs_[i]->uses().empty()` failed.

However, if I use onnxsim-0.4.31, I can successfully simplify the model.

**Comment by cferry-AMD** [comment]
[reproducer.onnx.gz](https://github.com/user-attachments/files/18487736/reproducer.onnx.gz)

The attached reproducer crashes, with the same issue, `onnxsim==0.4.36` but not `onnxsim==0.4.35`.
