### ISSUE TITLE
[Feature Request] Add support for fp8 QDQ models.

### ISSUE THREAD

**Issue by hopef** [daquexian/onnx-simplifier#348]
In the latest version of the onnx-simplifier, I have met errors on fp8 QDQ models.
- Error 1: shape inference
```bash
$> onnxsim fp8.onnx fp8-sim.onnx
Simplifying...
Traceback (most recent call last):
  File "/opt/conda3/bin/onnxsim", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda3/lib/python3.11/site-packages/onnxsim/onnx_simplifier.py", line 453, in main
    model_opt, check_ok = simplify(
                          ^^^^^^^^^
  File "/opt/conda3/lib/python3.11/site-packages/onnxsim/onnx_simplifier.py", line 187, in simplify
    model_opt_bytes = C.simplify(
                      ^^^^^^^^^^^
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:QuantizeLinear, node name: pts_bbox_head.transformer.decoder.layers.0.attentions.0.attn.query_quantizer/QuantizeLinear1): [TypeInferenceError] Inferred elem type differs from existing elem type: (17) vs (INT8)
```

- Error 2: CSETensorHash
```bash
$> onnxsim fp8.onnx fp8-sim.onnx --skip-shape-inference
Simplifying...
Traceback (most recent call last):
  File "/opt/conda3/bin/onnxsim", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda3/lib/python3.11/site-packages/onnxsim/onnx_simplifier.py", line 453, in main
    model_opt, check_ok = simplify(
                          ^^^^^^^^^
  File "/opt/conda3/lib/python3.11/site-packages/onnxsim/onnx_simplifier.py", line 187, in simplify
    model_opt_bytes = C.simplify(
                      ^^^^^^^^^^^
RuntimeError: no supported data type: 17
```

Could you please add support for fp8 QDQ models?
The fp8 QDQ models are aligned with [ModelOpt](https://github.com/NVIDIA/TensorRT-Model-Optimizer), which has the following architecture.
```python
x_scales = torch.ones(1, dtype=torch.float32)
x_zero_points = torch.zeros(1, dtype=torch.float8_e4m3fn)
w_scales = torch.ones(32, dtype=torch.float32)
w_zero_points= torch.zeros(32, dtype=torch.float8_e4m3fn)

x = Q(x, x_scales, x_zero_points)
x = DQ(x, x_scales, x_zero_points)

quant_weights = Q(weights, w_scales, w_zero_points)
quant_weights = DQ(quant_weights , w_scales, w_zero_points)
y = Conv(x, quant_weights)
```

**Comment by OValery16** [comment]
I also have the same problem

**Comment by congyang12345** [comment]
You can try using onnxslim

**Comment by take-cheeze** [comment]
Workaround added in https://github.com/onnxsim/onnxsim/pull/464

**Comment by take-cheeze** [comment]
Restoring simplifier backend in https://github.com/NVIDIA/Model-Optimizer/pull/2018
