### ISSUE TITLE
[ONNXRuntimeError] : 1 : FAIL : Node () Op (Concat) [ShapeInferenceError] rank must be greater than axis

### ISSUE THREAD

**Issue by TOM-tym** [daquexian/onnx-simplifier#46]
Hi, thanks for your simplifier.
I've met an error like this when I run command `python3 -m onnxsim model.onnx model_slim.onnx`
Simplifying...

> Traceback (most recent call last):
>   File "/home/tangym/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/tangym/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/tangym/anaconda3/lib/python3.6/site-packages/onnxsim/__main__.py", line 42, in <module>
>     main()
>   File "/home/tangym/anaconda3/lib/python3.6/site-packages/onnxsim/__main__.py", line 31, in main
>     args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization, input_shapes=input_shapes)
>   File "/home/tangym/anaconda3/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 303, in simplify
>     res = forward_all(model, input_shapes=input_shapes)
>   File "/home/tangym/anaconda3/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 158, in forward_all
>     res = forward(model, input_shapes=input_shapes)
>   File "/home/tangym/anaconda3/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 143, in forward
>     sess = rt.InferenceSession(model.SerializeToString(), sess_options=sess_options)
>   File "/home/tangym/anaconda3/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 25, in __init__
>     self._load_model(providers)
>   File "/home/tangym/anaconda3/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 43, in _load_model
>     self._sess.load_model(providers)
> onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node () Op (Concat) [ShapeInferenceError] rank must be greater than axis

I am actually transform my object detection model in pytorch into onnx. Here's some useful information (hope so). I am sure that my origin pytorch model has no error in concat operation (as described in the error message above)
Here is how I transform. I use command below in python script.
`torch.onnx.export(model, dummy_input, "alexnet.onnx", verbose=True, input_names=input_names, output_names=output_names)`

**Comment by TOM-tym** [comment]
Here's my onnx model structure. I print it out.
[model.txt](https://github.com/daquexian/onnx-simplifier/files/4249634/model.txt)

**Comment by daquexian** [comment]
Could you please send the .onnx model to my email daquexian566@gmail.com? It is not easy to parse the .txt file. Thanks!

**Comment by thanhtcptit** [comment]
Had you solved this issue ? I'm encountering this problem too and I'm sure that my pytorch graph is defined properly

**Comment by thanhtcptit** [comment]
For anyone finding this in the future, I've managed to fix this by remove the .unsqueeze() function from my graph as follow:
From
```
torch.cat((torch.mean(x, 1).unsqueeze(1), torch.mean(x, 1).unsqueeze(1)), dim=1)
```
to
```
torch.cat((torch.mean(x, 1, keepdim=True), torch.mean(x, 1, keepdim=True)), dim=1)
```
maybe it have to do with the way onnx-simplifier handle unsqueeze function
