### ISSUE TITLE
[BUG] Cannot pass python3 setup.py install on AGX

### ISSUE THREAD

**Issue by chiehpower** [daquexian/onnx-simplifier#55]
**Describe the bug**
Hi all, 

I wanna build an onnx-simplifier from source(GitHub) on my AGX. 
Because if I use the onnx-simplifier which was built from pip, it will get wrong.
```
Simplifying...
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/onnx_simplifier-0.0.0-py3.6.egg/onnxsim/__main__.py", line 46, in <module>
  File "/usr/local/lib/python3.6/dist-packages/onnx_simplifier-0.0.0-py3.6.egg/onnxsim/__main__.py", line 34, in main
  File "/usr/local/lib/python3.6/dist-packages/onnx_simplifier-0.0.0-py3.6.egg/onnxsim/onnx_simplifier.py", line 311, in simplify
  File "/usr/local/lib/python3.6/dist-packages/onnx_simplifier-0.0.0-py3.6.egg/onnxsim/onnx_simplifier.py", line 160, in forward_for_node_outputs
  File "/usr/local/lib/python3.6/dist-packages/onnx_simplifier-0.0.0-py3.6.egg/onnxsim/onnx_simplifier.py", line 144, in forward
TypeError: __init__() got an unexpected keyword argument 'providers'
```

So I git clone the latest version from github, and use this command:
```
$ sudo -H python3 setup.py install                                              
```
Then I got this version error
``` 
running install
running bdist_egg
running egg_info
writing onnx_simplifier.egg-info/PKG-INFO
writing dependency_links to onnx_simplifier.egg-info/dependency_links.txt
writing requirements to onnx_simplifier.egg-info/requires.txt
writing top-level names to onnx_simplifier.egg-info/top_level.txt
reading manifest file 'onnx_simplifier.egg-info/SOURCES.txt'
writing manifest file 'onnx_simplifier.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-aarch64/egg
running install_lib
running build_py
creating build/bdist.linux-aarch64/egg
creating build/bdist.linux-aarch64/egg/onnxsim
copying build/lib/onnxsim/__main__.py -> build/bdist.linux-aarch64/egg/onnxsim
copying build/lib/onnxsim/__init__.py -> build/bdist.linux-aarch64/egg/onnxsim
copying build/lib/onnxsim/onnx_simplifier.py -> build/bdist.linux-aarch64/egg/onnxsim
byte-compiling build/bdist.linux-aarch64/egg/onnxsim/__main__.py to __main__.cpython-36.pyc
byte-compiling build/bdist.linux-aarch64/egg/onnxsim/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-aarch64/egg/onnxsim/onnx_simplifier.py to onnx_simplifier.cpython-36.pyc
creating build/bdist.linux-aarch64/egg/EGG-INFO
copying onnx_simplifier.egg-info/PKG-INFO -> build/bdist.linux-aarch64/egg/EGG-INFO
copying onnx_simplifier.egg-info/SOURCES.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
copying onnx_simplifier.egg-info/dependency_links.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
copying onnx_simplifier.egg-info/requires.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
copying onnx_simplifier.egg-info/top_level.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/onnx_simplifier-0.0.0-py3.6.egg' and adding 'build/bdist.linux-aarch64/egg' to it
removing 'build/bdist.linux-aarch64/egg' (and everything under it)
Processing onnx_simplifier-0.0.0-py3.6.egg
Copying onnx_simplifier-0.0.0-py3.6.egg to /usr/local/lib/python3.6/dist-packages
Adding onnx-simplifier 0.0.0 to easy-install.pth file

Installed /usr/local/lib/python3.6/dist-packages/onnx_simplifier-0.0.0-py3.6.egg
Processing dependencies for onnx-simplifier==0.0.0
Searching for onnxruntime>=1.2.0
Reading https://pypi.org/simple/onnxruntime/
No local packages or working download links found for onnxruntime>=1.2.0
error: Could not find suitable distribution for Requirement.parse('onnxruntime>=1.2.0')
```
I was using onnxruntime-gpu version 1.0.0  
Is there any possible to build onnx-simplifier from onnxruntime 1.0.0 version?

Thank you.

# Env setting information
```
NVIDIA Jetson AGX Xavier - Jetpack 4.3 [L4T 32.3.1]
- Name: NVIDIA Jetson AGX Xavier
- Type: AGX Xavier
- Jetpack: 4.3 [L4T 32.3.1]
- CUDA: 10.0.326
- cuDNN: 7.6.3.28-1+cuda10.0
- TensorRT: 6.0.1.10-1+cuda10.0
- onnxrunime built from source. version 1.0.0
```

**Comment by daquexian** [comment]
QAQ Thanks for your issue. Whether AGX is supported by onnxsim greatly depends on onnxruntime but not onnxsim itself, so if you have an x86 machine, it is recommended to simplify the onnx model on x86 and then deploy the simplified model on other platform.

**Comment by chiehpower** [comment]
@daquexian  Thanks for your reply!
The thing is that I can run onnxruntime on AGX, but I cannot pass on building onnxsim.
According to what you said, could I conclude that onnxsim cannot support on AGX?

BTW Currently I used another way. Simplify onnx model on PC, and take this model on AGX.
