### ISSUE TITLE
onnx.onnx_cpp2py_export.checker.ValidationError: 126 in initializer but not in graph input

### ISSUE THREAD

**Issue by Mactarvish** [daquexian/onnx-simplifier#62]
I'm trying to simplify my .onnx model using onnx-simplifier, after executing `python -m onnxsim resnet.onnx resnet_simplified.onnx`, I got such error report:
`
Simplifying...
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/onnxsim/__main__.py", line 46, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/onnxsim/__main__.py", line 34, in main
    args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization, skip_fuse_bn=not args.enable_fuse_bn, input_shapes=input_shapes)
  File "/usr/local/lib/python3.5/dist-packages/onnxsim/onnx_simplifier.py", line 308, in simplify
    model = optimize(model, skip_fuse_bn)
  File "/usr/local/lib/python3.5/dist-packages/onnxsim/onnx_simplifier.py", line 231, in optimize
    onnx.checker.check_model(model)
  File "/usr/local/lib/python3.5/dist-packages/onnx/checker.py", line 91, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: 126 in initializer but not in graph input
`

How to fix it? Thanks in advance.

**Comment by daquexian** [comment]
could you please send your model to daquexian566@gmail.com? Thanks!

**Comment by Mactarvish** [comment]
It's been fixed, my pytorch is 1.0, updating to 1.2 solved this problem. Thanks anyway.
