### ISSUE TITLE
KeyError: 'conv3'

### ISSUE THREAD

**Issue by l0stpenguin** [daquexian/onnx-simplifier#67]
**Describe the bug**
I am trying to run the simplifier on a model with dynamic shape. As per documentation, i specified the input shape but the conversion fails. 

`python3 -m onnxsim dense.onnx simplified.onnx --input-shape 1,480,640,3`

Full log:
```
Simplifying...
Checking 0/3...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/onnxsim/__main__.py", line 48, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/onnxsim/__main__.py", line 36, in main
    args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization, skip_fuse_bn=not args.enable_fuse_bn, input_shapes=input_shapes)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 319, in simplify
    check_ok = check(model_ori, model, check_n, input_shapes=input_shapes)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 255, in check
    if not np.allclose(res_opt[name], res_ori[name], rtol=1e-4, atol=1e-5):
KeyError: 'conv3'
```
**Model**
model link: [densedepth.onnx](https://drive.google.com/file/d/1GIa2sK5QYvUhJ4dhHn1_wGA1k925uWZi/view?usp=sharing)

**Comment by daquexian** [comment]
thanks for your report! i will look into this issue. As a quick solution,
you can try `python3 -m onnxsim dense.onnx simplified.onnx 0 --input-shape
1,480,640,3` to skip the checking

**Comment by l0stpenguin** [comment]
thanks it worked.

**Comment by Zrufy** [comment]
same problem to me @daquexian.

```
Simplifying...
Checking 0/3...
Traceback (most recent call last):
  File "C:\Users\Anaconda3\envs\Tensorflow-CPU\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\vincenzo\envs\Tensorflow-CPU\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Anaconda3\envs\Tensorflow-CPU\lib\site-packages\onnxsim\__main__.py", line 48, in <module>
    main()
  File "C:\Users\Anaconda3\envs\Tensorflow-CPU\lib\site-packages\onnxsim\__main__.py", line 36, in main
    args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization, skip_fuse_bn=not args.enable_fuse_bn, input_shapes=input_shapes)
  File "C:\Users\vincenzo\Anaconda3\envs\Tensorflow-CPU\lib\site-packages\onnxsim\onnx_simplifier.py", line 319, in simplify
    check_ok = check(model_ori, model, check_n, input_shapes=input_shapes)
  File "C:\Users\Anaconda3\envs\Tensorflow-CPU\lib\site-packages\onnxsim\onnx_simplifier.py", line 255, in check
    if not np.allclose(res_opt[name], res_ori[name], rtol=1e-4, atol=1e-5):
KeyError: '236'
```

solved with the solution you have suggested.

**Comment by daquexian** [comment]
> same problem to me @daquexian.
> 
> ```
> Simplifying...
> Checking 0/3...
> Traceback (most recent call last):
>   File "C:\Users\Anaconda3\envs\Tensorflow-CPU\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "C:\Users\vincenzo\envs\Tensorflow-CPU\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\Anaconda3\envs\Tensorflow-CPU\lib\site-packages\onnxsim\__main__.py", line 48, in <module>
>     main()
>   File "C:\Users\Anaconda3\envs\Tensorflow-CPU\lib\site-packages\onnxsim\__main__.py", line 36, in main
>     args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization, skip_fuse_bn=not args.enable_fuse_bn, input_shapes=input_shapes)
>   File "C:\Users\vincenzo\Anaconda3\envs\Tensorflow-CPU\lib\site-packages\onnxsim\onnx_simplifier.py", line 319, in simplify
>     check_ok = check(model_ori, model, check_n, input_shapes=input_shapes)
>   File "C:\Users\Anaconda3\envs\Tensorflow-CPU\lib\site-packages\onnxsim\onnx_simplifier.py", line 255, in check
>     if not np.allclose(res_opt[name], res_ori[name], rtol=1e-4, atol=1e-5):
> KeyError: '236'
> ```
> 
> solved with the solution you have suggested.

thanks for your report. it is because of a bug in onnx built-in optimizer. i will disable the broken optimizer.
