### ISSUE TITLE
Attempting to broadcast an axis by a dimension other than 1. 16 by 96

### ISSUE THREAD

**Issue by veepersgit** [daquexian/onnx-simplifier#7]
Here's the error message:
Simplifying...
Traceback (most recent call last):
  File "/home/mywp/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mywp/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mywp/anaconda3/lib/python3.6/site-packages/onnxsim/__main__.py", line 24, in <module>
    main()
  File "/home/mywp/anaconda3/lib/python3.6/site-packages/onnxsim/__main__.py", line 17, in main
    model_opt = onnxsim.simplify(args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization)
  File "/home/mywp/anaconda3/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 187, in simplify
    model_opt = eliminate_const_nodes(model_opt, get_constant_nodes(model_opt), forward_all(model_opt))
  File "/home/mywp/anaconda3/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 105, in forward_all
    res = forward(model)
  File "/home/mywp/anaconda3/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 97, in forward
    res = OrderedDict(zip(outputs, sess.run(outputs, inputs)))
  File "/home/mywp/anaconda3/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 72, in run
    return self._sess.run(output_names, input_feed, run_options)
RuntimeError: Method run failed due to: [ONNXRuntimeError] : 1 : GENERAL ERROR : /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:341 void onnxruntime::BroadcastIterator::Init(int64_t, int64_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 16 by 96
Stacktrace:

**Comment by daquexian** [comment]
Thanks for your report! Could you please provide your ONNX model? You can send me by email: daquexian566@gmail.com

**Comment by daquexian** [comment]
It is a bug of pytorch->onnx converter. I have reported it to PyTorch: https://github.com/pytorch/pytorch/issues/21271

**Comment by daquexian** [comment]
It is solved in https://github.com/pytorch/pytorch/pull/21330. Closing it.

**Comment by weihua04** [comment]
> pytorch/pytorch#21330

i have met the same problem,how to install nightly PyTorch

**Comment by weihua04** [comment]
> It is solved in [pytorch/pytorch#21330](https://github.com/pytorch/pytorch/pull/21330). Please install nightly PyTorch and re-export the onnx model then try again.

thank u for reply, i have met the same problem ,could u tell me how to install nightly PyTorch? thank u very much

**Comment by daquexian** [comment]
> > It is solved in [pytorch/pytorch#21330](https://github.com/pytorch/pytorch/pull/21330). Please install nightly PyTorch and re-export the onnx model then try again.
> 
> thank u for reply, i have met the same problem ,could u tell me how to install nightly PyTorch? thank u very much

On https://pytorch.org/get-started/locally/, select "preview" to get the command

**Comment by daquexian** [comment]
I believe https://github.com/pytorch/pytorch/pull/21330 has been included in PyTorch 1.2, so it's better to install pytorch 1.2 than pytorch nightly
