### ISSUE TITLE
[BUG] : Fatal error: ATen is not a registered function/op

### ISSUE THREAD

**Issue by lunasdejavu** [daquexian/onnx-simplifier#74]
**Describe the bug**
I transform a model of pytorch (1.5.0) to onnx 
but the model can't be simplified
the error messages:
```
Warning: ATen was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/__main__.py", line 48, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/__main__.py", line 36, in main
    args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization, skip_fuse_bn=not args.enable_fuse_bn, input_shapes=input_shapes)
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/onnx_simplifier.py", line 311, in simplify
    res = forward_for_node_outputs(model, const_nodes, input_shapes=input_shapes)
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/onnx_simplifier.py", line 160, in forward_for_node_outputs
    res = forward(model, input_shapes=input_shapes)
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/onnx_simplifier.py", line 144, in forward
    sess = rt.InferenceSession(model.SerializeToString(), sess_options=sess_options, providers=['CPUExecutionProvider'])
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/session.py", line 158, in __init__
    self._load_model(providers)
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/session.py", line 177, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Fatal error: ATen is not a registered function/op
```
what should I do now?
**Model**
the model is over here.
https://drive.google.com/file/d/11TFjSJWRIDvWvKngM2upD8fqoATmJAyP/view?usp=sharing
To reproduce the problem, please post download link of your model here, or send your model to daquexian566@gmail.com

**Comment by daquexian** [comment]
It looks like a bug of PyTorch. "ATen" means PyTorch built-in op and should not present in the ONNX model without explicitly setting the export mode.
