### ISSUE TITLE
[BUG] IndexError: list index (2) out of range

### ISSUE THREAD

**Issue by arnoldfychen** [daquexian/onnx-simplifier#89]
**Describe the bug**
Hi dear guys,

Just now, I installed the latest onnx-simplifier-0.2.15 and executed command like "python -m onnsim efficientdet-d0.onnx efficientdet-d0-simplified.onnx" and got such an error:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/__main__.py", line 52, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/__main__.py", line 40, in main
    args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization, skip_fuse_bn=not args.enable_fuse_bn, input_shapes=input_shapes, skipped_optimizers=args.skip_optimizer, skip_shape_inference=args.skip_shape_inference)
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/onnx_simplifier.py", line 331, in simplify
    const_nodes = get_constant_nodes(model)
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/onnx_simplifier.py", line 140, in get_constant_nodes
    elif is_dynamic(node):
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/onnx_simplifier.py", line 131, in is_dynamic
    if node.op_type in ['Resize'] and (node.input[2] not in const_tensors or (len(node.input) > 3 and node.input[3] not in const_tensors)):
IndexError: list index (2) out of range

I checked the code in /usr/local/lib/python3.6/dist-packages/onnxsim/onnx_simplifier.py and made such a change at line 131:
 if node.op_type in ['Resize'] and (len(node.input)>2 and node.input[2] not in const_tensors or (len(node.input) > 3 and node.input[3] not in const_tensors)):

then error disappeared and  python -m onnxsim  worked well for my onnx.

**Comment by daquexian** [comment]
Thanks for your report!

It is a bug and your solution is right. Could you please submit a PR to fix it?   XD

**Comment by arnoldfychen** [comment]
It's not so urgent for me, it's OK You fix it in next release, thanks
