### ISSUE TITLE
[BUG] Segmentation fault on torchvision Mask RCNN model

### ISSUE THREAD

**Issue by coreystaten** [daquexian/onnx-simplifier#91]
Using Pytorch 1.6.0, torchvision 0.7.0, and onnx-simplifier 0.2.15, the following script seg faults during the call to `onnxsim.simplify`:

```
import onnxsim
import torch
import torchvision

model = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True)
model.eval()
x = [torch.rand(3, 300, 300)]
torch.onnx.export(model, x, "mask_rcnn.onnx", opset_version = 11)
model_simp, check = onnxsim.simplify('mask_rcnn.onnx')
```

I haven't posted a model file, since the above script generates one using torchvision.

Script output:
```
/home/user/.conda/envs/te/lib/python3.8/site-packages/torch/nn/functional.py:3009: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return [(torch.floor((input.size(i + 2).float() * torch.tensor(scale_factors[i],
/home/user/.conda/envs/te/lib/python3.8/site-packages/torchvision/models/detection/rpn.py:163: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  strides = [[torch.tensor(image_size[0] // g[0], dtype=torch.int64, device=device),
/home/user/.conda/envs/te/lib/python3.8/site-packages/torchvision/models/detection/rpn.py:164: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(image_size[1] // g[1], dtype=torch.int64, device=device)] for g in grid_sizes]
/home/user/.conda/envs/te/lib/python3.8/site-packages/torch/tensor.py:452: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  warnings.warn('Iterating over a tensor might cause the trace to be incorrect. '
/home/user/.conda/envs/te/lib/python3.8/site-packages/torchvision/ops/boxes.py:124: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  boxes_x = torch.min(boxes_x, torch.tensor(width, dtype=boxes.dtype, device=boxes.device))
/home/user/.conda/envs/te/lib/python3.8/site-packages/torchvision/ops/boxes.py:126: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  boxes_y = torch.min(boxes_y, torch.tensor(height, dtype=boxes.dtype, device=boxes.device))
/home/user/.conda/envs/te/lib/python3.8/site-packages/torchvision/ops/boxes.py:101: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629395347/work/torch/csrc/utils/python_arg_parser.cpp:766.)
  keep = keep.nonzero().squeeze(1)
/home/user/.conda/envs/te/lib/python3.8/site-packages/torchvision/models/detection/transform.py:269: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(s, dtype=torch.float32, device=boxes.device) /
/home/user/.conda/envs/te/lib/python3.8/site-packages/torchvision/models/detection/transform.py:270: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(s_orig, dtype=torch.float32, device=boxes.device)
/home/user/.conda/envs/te/lib/python3.8/site-packages/torchvision/models/detection/roi_heads.py:372: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return torch.tensor(M + 2 * padding).to(torch.float32) / torch.tensor(M).to(torch.float32)
/home/user/.conda/envs/te/lib/python3.8/site-packages/torch/onnx/symbolic_opset9.py:2221: UserWarning: Exporting aten::index operator of advanced indexing in opset 11 is achieved by combination of multiple ONNX operators, including Reshape, Transpose, Concat, and Gather. If indices include negative values, the exported graph will produce incorrect results.
  warnings.warn("Exporting aten::index operator of advanced indexing in opset " +
Segmentation fault (core dumped)
```

**Comment by daquexian** [comment]
Thanks for your report! I reproduced this problem in onnx 1.7 release. However, this problem disappeared when I compiled onnx from master. Could you please compile onnx from master and try again? Thanks!

**Comment by koenvandesande** [comment]
The segmentation fault is gone, but now there is another problem with the simplification:
```
model_simp, check = onnxsim.simplify('mask_rcnn.onnx')
WARNING: ONNX Optimizer has been moved to https://github.com/onnx/optimizer.
All further enhancements and fixes to optimizers will be done in this new repo.
The optimizer code in onnx/onnx repo will be removed in 1.9 release.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/miniconda3/envs/pytorch17/lib/python3.8/site-packages/onnxsim/onnx_simplifier.py", line 329, in simplify
    model = optimize(model, skip_fuse_bn, skipped_optimizers)
  File "/home/ubuntu/miniconda3/envs/pytorch17/lib/python3.8/site-packages/onnxsim/onnx_simplifier.py", line 249, in optimize
    model = onnx.optimizer.optimize(model, optimizers_list,
  File "/home/ubuntu/miniconda3/envs/pytorch17/lib/python3.8/site-packages/onnx-1.7.0-py3.8-linux-x86_64.egg/onnx/optimizer.py", line 53, in optimize
    optimized_model_str = C.optimize_fixedpoint(model_str, passes)
MemoryError: std::bad_alloc
```
Does that help?

**Comment by koenvandesande** [comment]
With this the segfault also does not occur:

```
model_simp, check = onnxsim.simplify('mask_rcnn.onnx', skipped_optimizers=[
    'eliminate_deadend', 'eliminate_nop_dropout',
    'eliminate_nop_monotone_argmax',
    'fuse_consecutive_concats',
    'fuse_consecutive_log_softmax',
    'fuse_consecutive_reduce_unsqueeze', 'fuse_consecutive_squeezes',
    'fuse_consecutive_transposes', 'fuse_matmul_add_bias_into_gemm',
    'fuse_pad_into_conv', 'fuse_transpose_into_gemm'
    ],
```

But the resulting model isn't parseable by e.g. TensorRT

**Comment by daquexian** [comment]
Thanks for your report! Could you please send the model to
daquexian566@gmail.com? Thanks!

**Comment by daquexian** [comment]
mask-rcnn is supported in the latest v0.2.23 onnx-simplifier  :D
