### ISSUE TITLE
onnx opset11 error

### ISSUE THREAD

**Issue by onexuan** [daquexian/onnx-simplifier#92]
Does it support onnx opset11?

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/onnxsim/__main__.py", line 52, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/onnxsim/__main__.py", line 39, in main
    model_opt, check_ok = onnxsim.simplify(
  File "/usr/local/lib/python3.8/site-packages/onnxsim/onnx_simplifier.py", line 321, in simplify
    onnx.checker.check_model(model)
  File "/usr/local/lib/python3.8/site-packages/onnx/checker.py", line 86, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Your model ir_version is higher than the checker's.

**Comment by onexuan** [comment]
close

**Comment by dzyjjpy** [comment]
@onexuan have you solve this issue? I met same one , looking forward to your reply. Thanks

**Comment by daquexian** [comment]
@dzyjjpy please upgrade your onnx by `pip3 install -U onnx`
