### ISSUE TITLE
Error during conversion ssd mobilenet

### ISSUE THREAD

**Issue by Zrufy** [daquexian/onnx-simplifier#95]
hi @daquexian i have converted my ssd model to onnx with this tutorial.
https://github.com/onnx/tensorflow-onnx/blob/master/tutorials/ConvertingSSDMobilenetToONNX.ipynb
But when i use onnxsim i have this error
```
Simplifying...
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\Tensorflow-CPU\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\Anaconda3\envs\Tensorflow-CPU\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Anaconda3\envs\Tensorflow-CPU\lib\site-packages\onnxsim\__main__.py", line 52, in <module>
    main()
  File "C:\Users\user\Anaconda3\envs\Tensorflow-CPU\lib\site-packages\onnxsim\__main__.py", line 40, in main
    args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization, skip_fuse_bn=not args.enable_fuse_bn, input_shapes=input_shapes, skipped_optimizers=args.skip_optimizer, skip_shape_inference=args.skip_shape_inference)
  File "C:\Users\user\Anaconda3\envs\Tensorflow-CPU\lib\site-packages\onnxsim\onnx_simplifier.py", line 329, in simplify
    model = optimize(model, skip_fuse_bn, skipped_optimizers)
  File "C:\Users\user\Anaconda3\envs\Tensorflow-CPU\lib\site-packages\onnxsim\onnx_simplifier.py", line 251, in optimize
    onnx.checker.check_model(model)
  File "C:\Users\user\Anaconda3\envs\Tensorflow-CPU\lib\site-packages\onnx\checker.py", line 93, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError
```
Can you help me to figure out is really important.

**Comment by daquexian** [comment]
Could you please try run onnxsim with `--skip-optimization`? Thanks!

**Comment by Zrufy** [comment]
the conversion works but the model triples its size and in the conversion in ncnn always gives me with error the presence of the cast layer @daquexian

**Comment by daquexian** [comment]
@Zrufy onnxsim doesn't help on the cast layer. Maybe you can join the ncnn telegram group and ask your question there: https://t.me/ncnnyes
