### ISSUE TITLE
Multiple inputs

### ISSUE THREAD

**Issue by edwardnguyen1705** [daquexian/onnx-simplifier#99]
Dear @arnaudbrejeon @daquexian ,

I want to simplify an `ONNX` [model](https://github.com/cleardusk/3DDFA_V2/blob/70e7cde4a893905c90bba08b66a69fae31917f07/bfm/bfm_onnx.py#L80) having multiple inputs:
```
    dummy_input = torch.randn(3, 3), torch.randn(
        3, 1), torch.randn(shape_dim, 1), torch.randn(exp_dim, 1)
    R, offset, alpha_shp, alpha_exp = dummy_input
    torch.onnx.export(
        bfm_decoder,
        (R, offset, alpha_shp, alpha_exp),
        bfm_onnx_fp,
        input_names=['R', 'offset', 'alpha_shp', 'alpha_exp'],
        output_names=['output'],
        dynamic_axes={
            'alpha_shp': [0],
            'alpha_exp': [0],
        },
        do_constant_folding=True
    )
```

I just use this script:
```
INPUT_SIZE=448
MODEL_NAME=bfm_noneck_v3
python -m onnxsim weights/onnx/${MODEL_NAME}.onnx weights/onnx/${MODEL_NAME}.onnx --input-shape 1,3,3,3,1,40,1,10,1
```
but errors appear:
```
Simplifying...
Traceback (most recent call last):
  File "/Users/thanhnguyen/miniconda3/envs/yolov5/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/thanhnguyen/miniconda3/envs/yolov5/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/thanhnguyen/miniconda3/envs/yolov5/lib/python3.7/site-packages/onnxsim/__main__.py", line 52, in <module>
    main()
  File "/Users/thanhnguyen/miniconda3/envs/yolov5/lib/python3.7/site-packages/onnxsim/__main__.py", line 40, in main
    args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization, skip_fuse_bn=not args.enable_fuse_bn, input_shapes=input_shapes, skipped_optimizers=args.skip_optimizer, skip_shape_inference=args.skip_shape_inference)
  File "/Users/thanhnguyen/miniconda3/envs/yolov5/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 326, in simplify
    input_shapes = check_and_update_input_shapes(model, input_shapes)
  File "/Users/thanhnguyen/miniconda3/envs/yolov5/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 306, in check_and_update_input_shapes
    'The model has more than 1 inputs, please use the format "input_name:dim0,dim1,...,dimN" in --input-shape')
RuntimeError: The model has more than 1 inputs, please use the format "input_name:dim0,dim1,...,dimN" in --input-shape
```

Do you have any suggestion?

**Comment by daquexian** [comment]
Sorry for the late reply. Please use netron.app to check what the input names are in your model, and then use `--input-shape the_input_name:dim0,dim1,..,dimN` instead of a simple `--input-shape dim0,dim1,...,dimN`
